SFSAcademy/SFSAcademy/Models/Attendance.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SFSAcademy;



namespace SFSAcademy
{
    public class AttendanceSubLeave
    {
        public int? Absentee_Id { get; set; }
        public int? Student_Id { get; set; }
        public string AttendanceDate { get; set; }
        public int? Batch_Id { get; set; }
        public int? Subject_Id { get; set; }
        public string Reason { get; set; }
        public bool Forenoon { get; set; }
        public bool Afternoon { get; set; }
        public string Next { get; set; }
    }
    public enum RANGE
    {
        Below,
        Above,
        Equals
    }
    public partial class ATTENDENCE : IValidatableObject
    {
        private SFSAcademyEntities db = new SFSAcademyEntities();
        private string ErrorMessage { get; set; }
        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            var Batch = db.BATCHes.Include(x => x.COURSE).Where(x => x.ID == BTCH_ID).FirstOrDefault();
            string BatchName = string.Concat(Batch.COURSE.CODE, "-", Batch.NAME);
            STUDENT std = db.STUDENTs.Find(STDNT_ID);
            if(STDNT_ID != null)
            {
                if(std.BTCH_ID != BTCH_ID)
                {
                    yield return new ValidationResult($"Attendance is not marked for present batch {BatchName}.", new[] { BatchName });
                }

            }
        }

        public IEnumerable<ValidationResult> After_Validate(ValidationContext validationContext)
        {
            if(MONTH_DATE != null)
            {
                if(STDNT_ID != null && MONTH_DATE < STUDENT.ADMSN_DATE)
                {
                    yield return new ValidationResult($"Attendance before the date of admission {STUDENT.ADMSN_DATE}.", new[] { ((DateTime)STUDENT.ADMSN_DATE).ToShortDateString() });
                }
            }
            else
            {
                ErrorMessage = "Month Date can not be blank";
                yield return new ValidationResult($"* {ErrorMessage}.", new[] { ErrorMessage });
            }
        }
        public bool Is_Full_Day()
        {
            if(FORENOON == true && PM == true)
            {
                return true;
            }
            else
            {
                return false;
            }
        }
        public bool Is_Half_Day()
        {
            if (FORENOON == true || PM == true)
            {
                return true;
            }
            else
            {
                return false;
            }
        }
    }
}

SFSAcademy/SFSAcademy/Models/News.cs
using System;
using System.Data;
using System.Linq;
using System.Web.UI.WebControls;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;
using System.Web.Mvc;

namespace SFSAcademy
{
    //public class NewsMaster
    //{
    //    public NEWS NewsData { get; set; }
    //    public NEWS_COMMENTS NewsCommentData { get; set; }
    //    public USER userData { get; set; }
    //}

    public class NewsComments
    {
        public int commentId { get; set; }
        public int? newsId { get; set; }
        public string commentContent { get; set; }
        public string commentAddedBy { get; set; }
        public int? AddedByUserId { get; set; }
        public DateTime? commentAddedDate { get; set; }
        public DateTime? commentUpdatedDate { get; set; }
        public bool? isApproved { get; set; }
        public string EnableNewsCommentModeration { get; set; }
        public User Author { get; set; }

        public void reload_news_bar()
        {
            //ActionHelper.expire_fragment(cache_fragment_name());
            News nw = new News();
            DataTable dt = nw.Get_Latest();
        }

        public string cache_fragment_name()
        {
            return "News_latest_fragment";
        }

    }

    public class NewsDetails
    {
        public int newsId { get; set; }
        [Required]
        [Display(Name = "News Title")]
        public string newsTitle { get; set; }
        [Required]
        [Display(Name = "News Content")]
        public string newsContent { get; set; }
        public DateTime? newsCreatedDate { get; set; }
        public DateTime? newsUpdatedDate { get; set; }
        [Display(Name = "Author of this News")]
        public string newsCreatedBy { get; set; }
        public int newsCommentCount { get; set; }
        public List<NewsComments> commentList { get; set; }
        public bool? isUserAdmin { get; set; }
        public bool? isModerator { get; set; }
        public int? CreatedByUserId { get; set; }
        public double days { get; set; }
        public string newsComment { get; set; }

        public User Author { get; set; }

        public void reload_news_bar()
        {
            //ActionHelper.expire_fragment(cache_fragment_name());
            News nw = new News();
            DataTable dt = nw.Get_Latest();
        }

        public string cache_fragment_name()
        {
            return "News_latest_fragment";
        }
    }
    public class News
    {
        private SFSAcademyEntities db = new SFSAcademyEntities();
        [Required]
        [Display(Name = "News Title")]
        public string Title { get; set; }

        [Required]
        [Display(Name = "News Content")]
        public string Content { get; set; }

        [Display(Name = "Author of this News")]
        public bool Author { get; set; }

        /// <summary>
        /// Checks if user with given password exists in the database
        /// </summary>
        /// <param name="_username">User name</param>
        /// <param name="_password">User password</param>
        /// <returns>True if user exist and password is correct</returns>

        [OutputCache(Duration = 10, VaryByParam = "*")]
        public DataTable Get_Latest()
        {
            var LatestNews = new DataTable();

            LatestNews.Columns.Add("Id", typeof(int));
            LatestNews.Columns.Add("NewsTitle", typeof(string));
            LatestNews.Columns.Add("NewsContent", typeof(string));
            LatestNews.Columns.Add("NewsDate", typeof(DateTime));

            var News = (from EV in db.NEWS
                        orderby EV.CREATED_AT descending
                        select new { ID = EV.ID, TITLE = EV.TIL, CONTENT = EV.CNTNT, DATE = EV.CREATED_AT }).Take(3);

            foreach (var entity in News.ToList())
            {
                var row = LatestNews.NewRow();
                row["Id"] = entity.ID;
                row["NewsTitle"] = entity.TITLE;
                row["NewsContent"] = entity.CONTENT;
                row["NewsDate"] = entity.DATE;
                LatestNews.Rows.Add(row);
            }
            return LatestNews;

        }
    }
}

SFSAcademy/SFSAcademy/Controllers/AttendancesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SFSAcademy;

namespace SFSAcademy.Controllers
{
    public class AttendancesController : Controller
    {
        private SFSAcademyEntities db = new SFSAcademyEntities();

        // GET: Attendances
        public ActionResult Index(string ErrorMessage, string Notice)
        {
            ViewBag.Notice = Notice;
            ViewBag.ErrorMessage = ErrorMessage;
            string config = db.CONFIGURATIONs.Where(x => x.CONFIG_KEY == "StudentAttendanceType").Select(x => x.CONFIG_VAL).FirstOrDefault().ToString();
            ViewBag.config = config;
            ViewBag.date_today = DateTime.Today.ToShortDateString();

            var batches = db.BATCHes.Where(x => x.ID == -1).DefaultIfEmpty().AsEnumerable();
            var current_user = this.Session["CurrentUser"] as UserDetails;
            int UserId = Convert.ToInt32(this.Session["UserId"]);
            var Employee = db.EMPLOYEEs.Where(x => x.USRID == UserId).FirstOrDefault();
            var employee_subjects = db.EMPLOYEES_SUBJECT.Where(x => x.EMP_ID == Employee.ID).ToList();
            if (current_user.User.ADMIN_IND == true)
            {
                batches = db.BATCHes.Include(x=>x.COURSE).FirstOrDefault().ACTIVE();
            }
            else if(current_user.privilage_list.Select(x=>x.NAME).Contains("StudentAttendanceRegister"))
            {
                batches = db.BATCHes.Include(x => x.COURSE).FirstOrDefault().ACTIVE();
            }
            else if(current_user.User.EMP_IND == true)
            {
                if(config == "Daily")
                {
                    batches = Employee.Employee_Batches();

                }
                else
                {
                    batches = Employee.Employee_Batches();
                    batches = batches.Union(employee_subjects.Select(x => x.SUBJECT.BATCH));
                    batches = batches.Distinct().ToList();
                }
            }
            List<SelectListItem> options = new SelectList(batches.OrderBy(x => x.ID), "ID", "Course_full_name").ToList();
            options.Insert(0, new SelectListItem() { Value = "-1", Text = "Select Batch" });
            ViewBag.BATCH_ID = options;
            return View();
        }

        // GET: Employee_Attendances
        public ActionResult List_Subject(int? batch_id)
        {
            bool allow_access = true;
            var current_user = this.Session["CurrentUser"] as UserDetails;
            int UserId = Convert.ToInt32(this.Session["UserId"]);
            var Employee = db.EMPLOYEEs.Where(x => x.USRID == UserId).FirstOrDefault();
            var employee_subjects = db.EMPLOYEES_SUBJECT.Where(x => x.EMP_ID == Employee.ID).ToList();
            if (batch_id != null)
            {
                BATCH batch = db.BATCHes.Find(batch_id);
                ViewData["batch"] = batch;
                //var subjects = db.BATCHes.Where(x => x.ID == batch_id).Select(x => x.SUBJECTs).ToList();
                var subjects = db.SUBJECTs.Where(x => x.BTCH_ID == batch_id).ToList();
                if (current_user.User.EMP_IND == true && allow_access == true && current_user.privilage_list.Select(x => x.NAME).Contains("StudentAttendanceRegister"))
                {
                    if(batch.Employees().Where(x=>x.ID == Employee.ID).FirstOrDefault() != null)
                    {
                        subjects = db.SUBJECTs.Where(x => x.BTCH_ID == batch_id).ToList();
                    }
                    else
                    {
                        subjects = db.SUBJECTs.Include(x=>x.EMPLOYEES_SUBJECT).Where(x => x.EMPLOYEES_SUBJECT.FirstOrDefault().EMP_ID == Employee.ID && x.BTCH_ID == batch_id).ToList();
                    }
                }
                List<SelectListItem> options = new SelectList(subjects.OrderBy(x => x.NAME), "ID", "NAME").ToList();
                options.Insert(0, new SelectListItem() { Value = "-1", Text = "Select Subject" });
                ViewBag.SUB_ID = options;
            }
            return PartialView("_Subjects");
        }

        // GET: Employee_Attendances
        public ActionResult Show(int? batch_id, int? subject_id, string next, string ErrorMessage)
        {
            ViewBag.ErrorMessage = ErrorMessage;
            string config = db.CONFIGURATIONs.Where(x => x.CONFIG_KEY == "StudentAttendanceType").Select(x => x.CONFIG_VAL).FirstOrDefault().ToString();
            ViewBag.config = config;
            DateTime today = System.DateTime.Today;
            if (next != "null")
            {
                today = Convert.ToDateTime(next);
            }
            ViewBag.today = today.ToShortDateString();
            ViewBag.today_Plus_1Month = today.AddMonths(1).ToShortDateString();
            ViewBag.today_Minus_1Month = today.AddMonths(-1).ToShortDateString();
            var start_date = new DateTime(today.Year, today.Month, 1);
            ViewBag.start_date = start_date;
            var end_date = start_date.AddMonths(1).AddDays(-1);
            ViewBag.end_date = end_date;
            List<DateTime> dates = new List<DateTime>();
            if (config == "Daily")
            {
                BATCH batch = db.BATCHes.Find(batch_id);
                ViewData["batch"] = batch;
                var Students = db.STUDENTs.Where(x => x.BTCH_ID == batch_id && x.IS_DEL == false && x.IS_ACT == true).ToList();
                ViewData["Students"] = Students;
                dates = batch.Working_Days(today);
                ViewData["dates"] = dates;
                ViewData["sub"] = db.SUBJECTs.Where(x=>x.ID == -1).FirstOrDefault();
            }
            else
            {
                SUBJECT sub = db.SUBJECTs.Find(subject_id);
                ViewData["sub"] = sub;
                BATCH batch = db.BATCHes.Find(batch_id);
                ViewData["batch"] = batch;
                if(sub.ELECTIVE_GRP_ID != null)
                {
                    var elective_student_ids = (from std in db.STUDENTs.Where(x=>x.IS_DEL == false && x.IS_ACT == true)
                                            join stdsub in db.STUDENT_SUBJECT on std.ID equals stdsub.STDNT_ID
                                            where stdsub.ID == subject_id
                                            select std).ToList();
                    var students = (from std in db.STUDENTs
                                    join elstd in elective_student_ids on std.ID equals elstd.ID
                                    where std.BTCH_ID == batch_id
                                    select std).ToList();
                    ViewData["students"] = students;
                }
                else
                {
                    var students_nonele = db.STUDENTs.Where(x=>x.BTCH_ID == batch_id && x.IS_DEL == false && x.IS_ACT == true).ToList();
                    ViewData["students"] = students_nonele;
                }
                dates = db.TIMETABLEs.FirstOrDefault().tte_for_range(batch, today, sub);
                ViewData["dates"] = dates;
            }
            return PartialView("_Register");
        }

        // GET: Employee_Attendances
        public ActionResult Edit(int? Abs_Id, string next)
        {
            string config = db.CONFIGURATIONs.Where(x => x.CONFIG_KEY == "StudentAttendanceType").Select(x => x.CONFIG_VAL).FirstOrDefault().ToString();
            ViewBag.config = config;
            //ATTENDENCE absenteeAt = db.ATTENDENCEs.Where(x => x.ID == -1).DefaultIfEmpty().FirstOrDefault();
            //SUBJECT_LEAVE absenteeSl = db.SUBJECT_LEAVE.Where(x => x.ID == -1).DefaultIfEmpty().FirstOrDefault();
            STUDENT student = db.STUDENTs.Where(x => x.ID == -1).DefaultIfEmpty().FirstOrDefault();
            SFSAcademy.AttendanceSubLeave AttendanceSL = new SFSAcademy.AttendanceSubLeave();
            AttendanceSL.Next = next;
            if (config == "Daily")
            {
                var absentee = db.ATTENDENCEs.Find(Abs_Id);
                AttendanceSL.AttendanceDate = absentee.MONTH_DATE.Value.ToShortDateString();
                AttendanceSL.Batch_Id = absentee.BTCH_ID;
                AttendanceSL.Student_Id = absentee.STDNT_ID;
                AttendanceSL.Absentee_Id = absentee.ID;
                AttendanceSL.Reason = absentee.RSN;
                AttendanceSL.Forenoon = absentee.FORENOON;
                AttendanceSL.Afternoon = absentee.PM;
                student = db.STUDENTs.Find(absentee.STDNT_ID);
            }
            else
            {
                var absentee = db.SUBJECT_LEAVE.Find(Abs_Id);
                AttendanceSL.AttendanceDate = absentee.MONTH_DATE.Value.ToShortDateString();
                AttendanceSL.Batch_Id = absentee.BTCH_ID;
                AttendanceSL.Student_Id = absentee.STDNT_ID;
                AttendanceSL.Subject_Id = absentee.SUBJECT_ID;
                AttendanceSL.Absentee_Id = absentee.ID;
                AttendanceSL.Reason = absentee.RSN;
                AttendanceSL.Subject_Id = absentee.SUBJECT_ID;
                student = db.STUDENTs.Find(absentee.STDNT_ID);
            }
            ViewData["student"] = student;
            return PartialView("_Edit", AttendanceSL);
        }

        [OutputCache(Duration = 0, VaryByParam = "*")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Update(SFSAcademy.AttendanceSubLeave AttendanceSL)
        {
            string config = db.CONFIGURATIONs.Where(x => x.CONFIG_KEY == "StudentAttendanceType").Select(x => x.CONFIG_VAL).FirstOrDefault().ToString();
            ViewBag.config = config;
            //ATTENDENCE absenteeAt = db.ATTENDENCEs.Where(x => x.ID == -1).DefaultIfEmpty().FirstOrDefault();

SFSAcademy/SFSAcademy/Views/Attendances/Index.cshtml
@model IEnumerable<SFSAcademy.ATTENDENCE>

@{
    ViewBag.Title = "Index";
}
<div id="content-header">
    <img src="~/Content/images/attendence/attendence.png" alt="Attendence Logo">
    <h1>Attendance</h1>
    <h3>Attendance Register</h3>
    <div id="app-back-button">
        <a href='javascript:history.back()' onclick="return confirm('are you sure?')"><img src="~/Content/images/buttons/back.png"></a>
    </div>
</div>
<div><img src="~/Content/images/_global/header_underline_.jpg" style="width:100%"></div>


<div id="page-yield">
    <div class="bread_crumb">
        <a href="@Url.Action("Index", "Student_Attendance")">Student Attendance</a> &raquo;
        Attendance Register
    </div>
    <div class="label-field-pair">
        <label>Select a Batch</label>
        <div class="text-input-bg">
            @if (ViewBag.config == "Daily")
            {
                @Html.DropDownList("BATCH_ID", null, htmlAttributes: new { @class = "form-control", @id = "BatchDropDown" })
            }
            else
            {
                @Html.DropDownList("BATCH_ID", null, htmlAttributes: new { @class = "form-control", @id = "SubBatchDropDown" })
            }
            <div class="LoaderBox"><img src="~/Content/images/loader.gif" id="loader" alt="Finance Logo" style="align-self:center; border:none"></div>
        </div>
    </div>
    <div id="subjects"></div>
    <div id="register"></div>
    <div id="modal-box" style="display:none;"></div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryunobtrusive") @*For unobtrusive-ajax*@
    @Scripts.Render("~/bundles/jqueryval") @*For validate and validate-unobtrusive*@

    <script type="text/javascript" language="javascript">
        $.ajaxSetup({ cache: false });
        $(document).ready(function () {
            $(".LoaderBox").hide();
            $('#BatchDropDown').change(function () {
                var selectedID = $(this).val();
                var SelectedNext = null;
                $(".LoaderBox").show();
                $.get('/Attendances/Show?batch_id=' + selectedID + "&next=" + SelectedNext, function (data) {
                    $('#register').html(data);
                    $('#register').fadeIn('fast');
                }).success(function (status) {
                    $(".LoaderBox").hide();
                });

            });
            $('#SubBatchDropDown').change(function () {
                var selectedID = $(this).val();
                var SelectedNext = null;
                $(".LoaderBox").show();
                $.get('/Attendances/List_Subject?batch_id=' + selectedID + "&next=" + SelectedNext, function (data) {
                    $('#subjects').html(data);
                    $('#subjects').fadeIn('fast');
                }).success(function (status) {
                    $(".LoaderBox").hide();
                });

            });
        });
    </script>
}

SFSAcademy/SFSAcademy/Views/Attendances/_Register.cshtml
@{
    SFSAcademyEntities db = new SFSAcademyEntities();
    List<DateTime> dates = (List<DateTime>)ViewData["dates"];
    IEnumerable<STUDENT> Students = (IEnumerable<STUDENT>)ViewData["Students"];
    SUBJECT sub = (SUBJECT)ViewData["sub"];
    BATCH batch = (BATCH)ViewData["batch"];
}
<script>
    $(document).ready(function () {
        $(".LoaderBox").hide();
    });
    function LoadPartialPage(sender) {
        $(".LoaderBox").show();
        $.get(sender, function (data) {
            $('#register').html(data);
            $('#register').fadeIn('fast');
        }).success(function (status) {
            $(".LoaderBox").hide();
        });
    }
    function LoadEditModelPage(sender) {
        $(".LoaderBox").show();
        $.get(sender, function (data) {
            $('#modal-box').html(data);
            $('#modal-box').fadeIn('fast');
        }).success(function (status) {
            $(".LoaderBox").hide();
            $('#modal-box').dialog('open');
        });
    }
    function LoadNewModelPage(sender) {
        $(".LoaderBox").show();
        $.get(sender, function (data) {
            $('#modal-box').html(data);
            $('#modal-box').fadeIn('fast');
        }).success(function (status) {
            $(".LoaderBox").hide();
            $('#modal-box').dialog('open');
        });
    }
    function LoadDeletePartialPage(sender) {
        $(".LoaderBox").show();
        if (confirm('Are you sure to delete this?')) {
            $.get(sender, function (data) {
                $('#register').html(data);
                $('#register').fadeIn('fast');
            }).success(function (status) {
                $(".LoaderBox").hide();
            });
        }
    }
</script>
@if (ViewBag.Notice != null)
{
    <p class="flash-msg"> @ViewBag.Notice </p>
}
@if (ViewBag.ErrorMessage != null)
{
    <p class="flash-msg"> @ViewBag.ErrorMessage </p>
}
<div class="header">
    @if (ViewBag.config == "Daily")
    {
        <div class="prev">
            <a href="@Url.Action("Show", "Attendances",new {batch_id = batch.ID, next = ViewBag.today_Minus_1Month })" onclick='LoadPartialPage(this.href); return false;'>◄</a>
        </div>
        <div class="month">
            @ViewBag.today
        </div>
        <div class="next">
            <a href="@Url.Action("Show", "Attendances",new {batch_id = batch.ID, next = ViewBag.today_Plus_1Month })" onclick='LoadPartialPage(this.href); return false;'>►</a>
        </div>
    }
    else
    {
        <div class="prev">
            <a href="@Url.Action("Show", "Attendances",new {batch_id = batch.ID, subject_id = sub.ID, next = ViewBag.today_Minus_1Month })" onclick='LoadPartialPage(this.href); return false;'>◄</a>
        </div>
        <div class="month">
            @ViewBag.today
        </div>
        <div class="next">
            <a href="@Url.Action("Show", "Attendances",new {batch_id = batch.ID, subject_id = sub.ID, next = ViewBag.today_Plus_1Month })" onclick='LoadPartialPage(this.href); return false;'>►</a>
        </div>
    }
    <div class="extender"></div>
</div>
<div class="box-1">
    <table class="" align="center" width="100%">
        <tr class="tr-head">
            <td class="head-td-name">Name</td>
            @{ DateTime current_day = DateTime.Today;}
            @if (ViewBag.config == "Daily")
            {
                foreach (var date in dates)
                {
                    if (current_day.ToShortDateString() == date.ToShortDateString())
                    {
                        <td class="head-td-date active"><div class="day">@date.Day</div> <div class="date"> @date.Month</div></td>
                    }
                    else
                    {
                        <td class="head-td-date"><div class="day">@date.Day</div> <div class="date"> @date.Month</div></td>
                    }
                }
            }
            else
            {
                foreach (var date in dates)
                {
                    if (current_day.ToShortDateString() == date.ToShortDateString())
                    {
                        <td class="head-td-date active"><div class="day">@date.Day</div> <div class="date"> @date.Month</div></td>
                    }
                    else
                    {
                        <td class="head-td-date"><div class="day">@date.Day</div> <div class="date"> @date.Month</div></td>
                    }
                }
            }
        </tr>
        @{ int i = 0;}
        @foreach (var student in Students)
        {
            string selectedRow = "tr-even";
            if (i % 2 == 0)
            {
                selectedRow = "tr-odd";
            }
            <tr class="@selectedRow">
                <td class="td-name">
                    @student.FIRST_NAME
                    <div class="date">
                        <span><div>@student.FIRST_NAME @student.MID_NAME @student.LAST_NAME</div></span>
                    </div>

                </td>
                @if (ViewBag.config == "Daily")
                {
                    foreach (var date in dates)
                    {
                        var absetNotNull = db.ATTENDENCEs.Where(x => x.MONTH_DATE != null).ToList();
                        var absent = absetNotNull.Where(x => x.STDNT_ID == student.ID && x.MONTH_DATE.Value.ToShortDateString() == date.ToShortDateString()).FirstOrDefault();
                        if (current_day.ToShortDateString() == date.ToShortDateString())
                        {
                            <td id="attendance-student-@student.ID -class-hour-@date.ToShortDateString()" class="td-mark active">
                                @if (absent != null && absent.ID != 0)
                                {
                                    <a href="@Url.Action("Edit", "Attendances",new {Abs_Id = absent.ID, next = ViewBag.today})" class="absent" onclick='LoadEditModelPage(this.href); return false;'>X</a>
                                    <a href="@Url.Action("Destroy", "Attendances",new {Abs_Id = absent.ID, next = ViewBag.today})" style="border:none" class="absent themed_text" onclick='LoadDeletePartialPage(this.href); return false;'><img src="~/Content/images/buttons/delete-new.png"></a>
                                }
                                else
                                {
                                    <a href="@Url.Action("New", "Attendances",new {Month_date =date, student_id = student.ID , next = ViewBag.today})" class="present" onclick='LoadNewModelPage(this.href); return false;'>O</a>
                                }
                                <div class="date">
                                    <div> <span> @date.ToShortDateString() @student.FIRST_NAME @student.MID_NAME @student.LAST_NAME</span> </div>
                                </div>
                            </td>
                        }
                        else
                        {
                            <td id="attendance-student-@student.ID -class-hour-@date.ToShortDateString()" class="td-mark">
                                @if (absent != null && absent.ID != 0)
                                {
                                    <a href="@Url.Action("Edit", "Attendances",new {Abs_Id = absent.ID, next = ViewBag.today})" class="absent" onclick='LoadEditModelPage(this.href); return false;'>X</a>
                                    <a href="@Url.Action("Destroy", "Attendances",new {Abs_Id = absent.ID, next = ViewBag.today})" style="border:none" class="absent themed_text" onclick='LoadDeletePartialPage(this.href); return false;'><img src="~/Content/images/buttons/delete-new.png"></a>
                                }
                                else
                                {
                                    <a href="@Url.Action("New", "Attendances",new {Month_date =date, student_id = student.ID , next = ViewBag.today})" class="present" onclick='LoadNewModelPage(this.href); return false;'>O</a>
                                }
                                <div class="date">
                                    <div> <span> @date.ToShortDateString() @student.FIRST_NAME @student.MID_NAME @student.LAST_NAME</span> </div>
                                </div>
                            </td>
                        }
                    }
                }
                else
                {
                    foreach (var date in dates)
                    {
                        var absent = db.SUBJECT_LEAVE.Where(x => x.STDNT_ID == student.ID && x.MONTH_DATE == date && x.SUBJECT_ID == sub.ID).FirstOrDefault();
                        if (current_day.ToShortDateString() == date.ToShortDateString())
                        {
                            <td id="attendance-student-@student.ID -date-@date.ToShortDateString()" class="td-mark active">
                                @if (absent != null && absent.ID != 0)
                                {
                                    <a href="@Url.Action("Edit", "Attendances",new {Abs_Id = absent.ID, next = ViewBag.today})" class="absent" onclick='LoadEditModelPage(this.href); return false;'>X</a>
                                    <a href="@Url.Action("Destroy", "Attendances",new {Abs_Id = absent.ID, next = ViewBag.today})" style="border:none" class="absent themed_text" onclick='LoadDeletePartialPage(this.href); return false;'><img src="~/Content/images/buttons/delete-new.png"></a>
                                }
                                else
                                {
                                    <a href="@Url.Action("New", "Attendances",new {Month_date =date, student_id = student.ID, subject_id = sub.ID , next = ViewBag.today})" class="present" onclick='LoadNewModelPage(this.href); return false;'>O</a>
                                }
                                <div class="date">
                                    <div> <span> @date.ToShortDateString() @student.FIRST_NAME @student.MID_NAME @student.LAST_NAME</span> </div>
                                </div>
                            </td>
                        }
                        else
                        {
                            <td id="attendance-student-@student.ID -date-@date.ToShortDateString()" class="td-mark">
                                @if (absent != null && absent.ID != 0)
                                {
                                    <a href="@Url.Action("Edit", "Attendances",new {Abs_Id = absent.ID, next = ViewBag.today})" class="absent" onclick='LoadEditModelPage(this.href); return false;'>X</a>
                                    <a href="@Url.Action("Destroy", "Attendances",new {Abs_Id = absent.ID, next = ViewBag.today})" style="border:none" class="absent themed_text" onclick='LoadDeletePartialPage(this.href); return false;'><img src="~/Content/images/buttons/delete-new.png"></a>
                                }
                                else
                                {
                                    <a href="@Url.Action("New", "Attendances",new {Month_date =date, student_id = student.ID, subject_id = sub.ID, next = ViewBag.today})" class="present" onclick='LoadNewModelPage(this.href); return false;'>O</a>
                                }
                                <div class="date">
                                    <div> <span> @date.ToShortDateString() @student.FIRST_NAME @student.MID_NAME @student.LAST_NAME</span> </div>
                                </div>
                            </td>
                        }
                    }
                }
            </tr>
        }
    </table>
</div>