SFSAcademy/SFSAcademy/Models/News.cs
using System;
using System.Data;
using System.Linq;
using System.Web.UI.WebControls;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;
using System.Web.Mvc;

namespace SFSAcademy
{
    //public class NewsMaster
    //{
    //    public NEWS NewsData { get; set; }
    //    public NEWS_COMMENTS NewsCommentData { get; set; }
    //    public USER userData { get; set; }
    //}

    public class NewsComments
    {
        public int commentId { get; set; }
        public int? newsId { get; set; }
        public string commentContent { get; set; }
        public string commentAddedBy { get; set; }
        public int? AddedByUserId { get; set; }
        public DateTime? commentAddedDate { get; set; }
        public DateTime? commentUpdatedDate { get; set; }
        public bool? isApproved { get; set; }
        public string EnableNewsCommentModeration { get; set; }
        public User Author { get; set; }

        public void reload_news_bar()
        {
            //ActionHelper.expire_fragment(cache_fragment_name());
            News nw = new News();
            DataTable dt = nw.Get_Latest();
        }

        public string cache_fragment_name()
        {
            return "News_latest_fragment";
        }

    }

    public class NewsDetails
    {
        public int newsId { get; set; }
        [Required]
        [Display(Name = "News Title")]
        public string newsTitle { get; set; }
        [Required]
        [Display(Name = "News Content")]
        public string newsContent { get; set; }
        public DateTime? newsCreatedDate { get; set; }
        public DateTime? newsUpdatedDate { get; set; }
        [Display(Name = "Author of this News")]
        public string newsCreatedBy { get; set; }
        public int newsCommentCount { get; set; }
        public List<NewsComments> commentList { get; set; }
        public bool? isUserAdmin { get; set; }
        public bool? isModerator { get; set; }
        public int? CreatedByUserId { get; set; }
        public double days { get; set; }
        public string newsComment { get; set; }

        public User Author { get; set; }

        public void reload_news_bar()
        {
            //ActionHelper.expire_fragment(cache_fragment_name());
            News nw = new News();
            DataTable dt = nw.Get_Latest();
        }

        public string cache_fragment_name()
        {
            return "News_latest_fragment";
        }
    }
    public class News
    {
        private SFSAcademyEntities db = new SFSAcademyEntities();
        [Required]
        [Display(Name = "News Title")]
        public string Title { get; set; }

        [Required]
        [Display(Name = "News Content")]
        public string Content { get; set; }

        [Display(Name = "Author of this News")]
        public bool Author { get; set; }

        /// <summary>
        /// Checks if user with given password exists in the database
        /// </summary>
        /// <param name="_username">User name</param>
        /// <param name="_password">User password</param>
        /// <returns>True if user exist and password is correct</returns>

        [OutputCache(Duration = 10, VaryByParam = "*")]
        public DataTable Get_Latest()
        {
            var LatestNews = new DataTable();

            LatestNews.Columns.Add("Id", typeof(int));
            LatestNews.Columns.Add("NewsTitle", typeof(string));
            LatestNews.Columns.Add("NewsContent", typeof(string));
            LatestNews.Columns.Add("NewsDate", typeof(DateTime));

            var News = (from EV in db.NEWS
                        orderby EV.CREATED_AT descending
                        select new { ID = EV.ID, TITLE = EV.TIL, CONTENT = EV.CNTNT, DATE = EV.CREATED_AT }).Take(3);

            foreach (var entity in News.ToList())
            {
                var row = LatestNews.NewRow();
                row["Id"] = entity.ID;
                row["NewsTitle"] = entity.TITLE;
                row["NewsContent"] = entity.CONTENT;
                row["NewsDate"] = entity.DATE;
                LatestNews.Rows.Add(row);
            }
            return LatestNews;

        }
    }
}

SFSAcademy/SFSAcademy/Controllers/Class_TimingsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SFSAcademy;

namespace SFSAcademy.Controllers
{
    public class Class_TimingsController : Controller
    {
        private SFSAcademyEntities db = new SFSAcademyEntities();

        // GET: Class_Timings
        public ActionResult Index(string Notice, string ErrorMessage)
        {
            ViewBag.Notice = Notice;
            ViewBag.ErrorMessage = ErrorMessage;

            var Class_Timings_Entry = db.CLASS_TIMING_SET.Where(x=>x.IS_DEL ==false);
            return View(Class_Timings_Entry.ToList());
        }

        // GET: Class_Timings/Create
        public ActionResult Class_TimingSet_View(int? id, string Notice, string ErrorMessage)
        {
            ViewBag.Notice = Notice;
            ViewBag.ErrorMessage = ErrorMessage;
            CLASS_TIMING_SET Class_Timing_Set = db.CLASS_TIMING_SET.Find(id);
            ViewData["Class_Timing_Set"] = Class_Timing_Set;

            var PeriodEntry = db.PERIOD_ENTRIES.ToList();
            ViewData["PeriodEntry"] = PeriodEntry;
            var Class_Timing_Entries = db.CLASS_TIMING_ENTRY.Include(x=>x.CLASS_TIMING_SET).Where(x => x.CLASS_TIMING_SET_ID == id && x.IS_DEL == false).OrderBy(x => x.START_TIME);
            ViewBag.CLASS_TIMING_SET_ID = id;
            return View(Class_Timing_Entries.ToList());
        }


        // GET: Class_Timings/Create
        public ActionResult Class_TimingSet_New()
        {          
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Class_TimingSet_New([Bind(Include = "ID,NAME,CREATED_AT,UPDATED_AT,IS_DEL")] CLASS_TIMING_SET cLASS_TIMING_sET)
        {
            if (ModelState.IsValid)
            {
                cLASS_TIMING_sET.UPDATED_AT = DateTime.Now;
                cLASS_TIMING_sET.CREATED_AT = DateTime.Now;
                db.CLASS_TIMING_SET.Add(cLASS_TIMING_sET);
                db.SaveChanges();
                ViewBag.Notice = "Class timing set was successfully created.";
                return RedirectToAction("Index", new { Notice = ViewBag.Notice });
            }
            ViewBag.Notice = "There seems to be some issue with Model State.";
            return View();
        }

        // GET: Class_Timings/Create
        public ActionResult Class_TimingSet_Delete(int? id)
        {
            CLASS_TIMING_SET Class_Timing_Set = db.CLASS_TIMING_SET.Find(id);
            var Class_Timing_Entry = db.CLASS_TIMING_ENTRY.Where(x => x.CLASS_TIMING_SET_ID == Class_Timing_Set.ID).ToList();

            foreach(var item in Class_Timing_Entry)
            {
                db.CLASS_TIMING_ENTRY.Remove(item);
            }
            db.CLASS_TIMING_SET.Remove(Class_Timing_Set);
            try { db.SaveChanges(); }
            catch (DbEntityValidationException e)
            {
                foreach (var eve in e.EntityValidationErrors) { foreach (var ve in eve.ValidationErrors) { ViewBag.ErrorMessage = string.Concat(ViewBag.ErrorMessage, "|", ve.ErrorMessage); } }
                return RedirectToAction("Index", new { ErrorMessage = ViewBag.ErrorMessage, Notice = ViewBag.Notice });
            }
            catch (Exception e)
            {
                ViewBag.ErrorMessage = string.Concat(ViewBag.ErrorMessage, "|", string.Concat(e.GetType().FullName, ":", e.Message));
                return RedirectToAction("Index", new {ErrorMessage = ViewBag.ErrorMessage, Notice = ViewBag.Notice });
            }
            ViewBag.Notice = string.Concat("Class Timing Set deleted successfully.");
            return RedirectToAction("Index", new {ErrorMessage = ViewBag.ErrorMessage, Notice = ViewBag.Notice });
        }

        // GET: Class_Timings/Create
        public ActionResult New(int? id)
        {
            CLASS_TIMING_SET Class_Timing_Set = db.CLASS_TIMING_SET.Find(id);
            ViewData["Class_Timing_Set"] = Class_Timing_Set;
            return PartialView("_New");
        }

        // POST: Class_Timings/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,CLASS_TIMING_SET_ID,NAME,START_TIME,END_TIME,IS_BRK,IS_DEL")] CLASS_TIMING_ENTRY cLASS_TIMING_ENTRY, int? CLASS_TIMING_SET_ID)
        {
            if (ModelState.IsValid)
            {
                cLASS_TIMING_ENTRY.CLASS_TIMING_SET_ID = CLASS_TIMING_SET_ID;
                cLASS_TIMING_ENTRY.IS_DEL = false;
                db.CLASS_TIMING_ENTRY.Add(cLASS_TIMING_ENTRY);
                db.SaveChanges();
                ViewBag.Notice = "Class timing entry was successfully created.";
                return RedirectToAction("Class_TimingSet_View", new { id= CLASS_TIMING_SET_ID, Notice = ViewBag.Notice});
            }

            ViewBag.ErrorMessage = "There seems to be some issue with Model State.";
            return RedirectToAction("Class_TimingSet_View", new { id = CLASS_TIMING_SET_ID, ErrorMessage = ViewBag.ErrorMessage });
        }

        // GET: Class_Timings/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CLASS_TIMING_ENTRY cLASS_TIMING_ENTRY = db.CLASS_TIMING_ENTRY.Include(x=>x.CLASS_TIMING_SET).Where(x=>x.ID == id).FirstOrDefault();
            CLASS_TIMING_SET Class_Timing_Set = db.CLASS_TIMING_SET.Find(cLASS_TIMING_ENTRY.CLASS_TIMING_SET_ID);
            ViewData["Class_Timing_Set"] = Class_Timing_Set;
            if (cLASS_TIMING_ENTRY == null)
            {
                return HttpNotFound();
            }
            return PartialView("_Edit", cLASS_TIMING_ENTRY);
        }

        // POST: Class_Timings/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Update([Bind(Include = "ID,CLASS_TIMING_SET_ID,NAME,START_TIME,END_TIME,IS_BRK,IS_DEL")] CLASS_TIMING_ENTRY cLASS_TIMING_ENTRY, int? CLASS_TIMING_SET_ID)
        {
            if (ModelState.IsValid)
            {
                CLASS_TIMING_ENTRY cLASS_TIMING_ENTRY_Update = db.CLASS_TIMING_ENTRY.Find(cLASS_TIMING_ENTRY.ID);
                cLASS_TIMING_ENTRY_Update.CLASS_TIMING_SET_ID = CLASS_TIMING_SET_ID;
                cLASS_TIMING_ENTRY_Update.NAME = cLASS_TIMING_ENTRY.NAME;
                cLASS_TIMING_ENTRY_Update.START_TIME = cLASS_TIMING_ENTRY.START_TIME;
                cLASS_TIMING_ENTRY_Update.END_TIME = cLASS_TIMING_ENTRY.END_TIME;
                cLASS_TIMING_ENTRY_Update.IS_BRK = cLASS_TIMING_ENTRY.IS_BRK;
                cLASS_TIMING_ENTRY_Update.IS_DEL = false;
                db.Entry(cLASS_TIMING_ENTRY_Update).State = EntityState.Modified;
                db.SaveChanges();
                ViewBag.Notice = "Class timing updated successfully.";
                return RedirectToAction("Class_TimingSet_View", new { id = CLASS_TIMING_SET_ID, Notice = ViewBag.Notice });
            }
            ViewBag.ErrorMessage = "There seems to be some issue with the Model State.";
            return RedirectToAction("Class_TimingSet_View", new { id = CLASS_TIMING_SET_ID, ErrorMessage = ViewBag.ErrorMessage });
        }

        // GET: Class_Timings/Delete/5
        public ActionResult Destroy(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CLASS_TIMING_ENTRY cLASS_TIMING_ENTRY = db.CLASS_TIMING_ENTRY.Find(id);
            int? CLASS_TIMING_SET_ID = cLASS_TIMING_ENTRY.CLASS_TIMING_SET_ID;
            if (cLASS_TIMING_ENTRY == null)
            {
                return HttpNotFound();
            }
            db.CLASS_TIMING_ENTRY.Remove(cLASS_TIMING_ENTRY);
            db.SaveChanges();
            ViewBag.Notice = "Class timing entry deleted successfully.";
            return RedirectToAction("Class_TimingSet_View", new { id = CLASS_TIMING_SET_ID, Notice = ViewBag.Notice });
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SFSAcademy/SFSAcademy/Views/Class_Timings/Class_TimingSet_New.cshtml
@model SFSAcademy.CLASS_TIMING_SET
@{
    ViewBag.Title = "Class_TimingSet_New";
}

<div id="content-header">
    <img src="~/Content/images/show_timetable.png" alt="Timetable Logo">
    <h1>Timetable</h1>
    <h3>Create Class Timing Set</h3>
    <div id="app-back-button">
        <a href='javascript:history.back()' onclick="return confirm('are you sure?')"><img src="~/Content/images/buttons/back.png"></a>
    </div>
</div>
<div><img src="~/Content/images/_global/header_underline_.jpg" style="width:100%"></div>
<div id="inner-tab-menu">
    <ul>
        <li>@Html.ActionLink("Class Timings", "Index")</li>
    </ul>
</div>
<div class="bread_crumb">
    <a href="@Url.Action("Index", "Timetable")"> Timetable &raquo; </a>
    @Html.ActionLink("Class Timing Sets", "Index") &raquo;
    New
</div>
<div id="page-yield">
    @if (ViewBag.Notice != null)
    {
        <p class="flash-msg"> @ViewBag.Notice </p>
    }

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="label-field-pair label">
            @Html.LabelFor(model => model.NAME, "Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <span class="necessary-field" style="font-size:small">* Required Field</span>
            <div class="text-input-bg">
                @Html.EditorFor(model => model.NAME, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.NAME, "", new { @class = "text-danger" })
            </div>
        </div>

        <input type="submit" value="► Submit" class="user_button" />
    }

</div>

SFSAcademy/SFSAcademy/Views/Class_Timings/Class_TimingSet_View.cshtml
@model IEnumerable<SFSAcademy.CLASS_TIMING_ENTRY>
@{
    SFSAcademy.CLASS_TIMING_SET Class_Timing_Set = (SFSAcademy.CLASS_TIMING_SET)ViewData["Class_Timing_Set"];
    IEnumerable<SFSAcademy.PERIOD_ENTRIES> PeriodEntry = (IEnumerable<SFSAcademy.PERIOD_ENTRIES>)ViewData["PeriodEntry"];
}
@{
    ViewBag.Title = "Class_Timing_View";
}

<script type="text/javascript" src="@Url.Content("~/Content/javascripts/jquery/jquery.min.js")"></script>
<script type="text/javascript" src="@Url.Content("~/Content/javascripts/jquery/jquery-ui.min.js")"></script>
<script type="text/javascript" src="@Url.Content("~/Content/javascripts/jquery/jquery-1.9.1.js")"></script>
<script type="text/javascript" src="@Url.Content("~/Content/javascripts/jquery/jquery-ui.js")"></script>

<script type="text/javascript" src="@Url.Content("~/Content/javascripts/jquery/jquery.timepicker.js")"></script>
<script type="text/javascript" src="@Url.Content("~/Content/javascripts/jquery/jquery.timepicker.min.js")"></script>
<link rel="stylesheet" href="~/Content/stylesheets/_styles/jquery.timepicker.css"/>
<link rel="stylesheet" href="~/Content/stylesheets/_styles/jquery.timepicker.min.css"/>
<link rel="stylesheet" href="~/Content/stylesheets/_styles/jquery-ui.css" />

<script type="text/javascript" src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.min.js")"></script>
<script type="text/javascript" src="@Url.Content("~/Scripts/jquery.validate.min.js")"></script>
<script type="text/javascript" src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")"></script>
<link rel="stylesheet" href="~/Content/stylesheets/_styles/jquery.ui.all.css" />


<script type="text/javascript" language="javascript">

    //Very similar function as before (except this time with an argument)
    function LoadOneClickPartialPage(sender) {
        $(".LoaderBox").show();
        /* Request the partial view with .get request. */
        $.get(sender, function (data) {

            /* data is the pure html returned from action method, load it to your page */
            $('#modal-box').html(data);
            /* little fade in effect */
            $('#modal-box').fadeIn('fast');
        }).success(function (status) {
            $(".LoaderBox").hide();
        });
    }
</script>
<div id="content-header">
    <img src="~/Content/images/show_timetable.png" alt="Timetable Logo">
    <h1>Timetable</h1>
    <h3>Set Class Timings</h3>
    <div id="app-back-button">
        <a href='javascript:history.back()' onclick="return confirm('are you sure?')"><img src="~/Content/images/buttons/back.png"></a>
    </div>
</div>
<div><img src="~/Content/images/_global/header_underline_.jpg" style="width:100%"></div>
<div class="bread_crumb">
    <a href="@Url.Action("Index", "Timetable")"> Timetable &raquo; </a>
    @Html.ActionLink("Class Timing Sets", "Index") &raquo;
    @Class_Timing_Set.NAME
</div>
<div id="page-yield">
    @if (ViewBag.Notice != null)
    {
        <p class="flash-msg"> @ViewBag.Notice </p>
    }

    <div class="box">
        @if (ViewBag.ErrorMessage != null)
        {
            <p class="flash-msg"> @ViewBag.ErrorMessage </p>
        }
        @{ string NameString = string.Concat("Class timing set name : ", @Class_Timing_Set.NAME);}
        @Html.Label("NAME", NameString, htmlAttributes: new { @class = "control-label col-md-2" })
        @Html.ActionLink("Edit", "Index")
        <div class="linker">
            <a href="@Url.Action("New", "Class_Timings",new {id= ViewBag.CLASS_TIMING_SET_ID })" onclick='LoadOneClickPartialPage(this.href); return false;'>Add Class Timing</a>
        </div>
        @if (Model != null && Model.Count() != 0)
        {
            <table id="class-timings-list" style="width:100%">
                <tr class="tr-head">
                    <td>Name</td>
                    <td>Start Time</td>
                    <td>End Time</td>
                    <td>Operations</td>
                </tr>
                @{int i = 1;}
                @foreach (var item in Model)
                {
                    string code = "tr-even";
                    if (i % 2 == 0)
                    {
                        code = "tr-odd";
                    }
                    <tr id="class-timing-@item.ID" class="@code">
                        <td class="col-1">@item.NAME</td>
                        @if (item.START_TIME != null)
                        {
                            <td class="col-3">@item.START_TIME</td>
                        }
                        else
                        {
                            <td class="col-3"> </td>}
                        @if (item.END_TIME != null)
                        {
                            <td class="col-3">@item.END_TIME</td>
                        }
                        else
                        {
                            <td class="col-3"> </td>}
                        <td class="col-3">
                            <small>
                                <a href="@Url.Action("Edit", "Class_Timings",new {id=item.ID})" onclick='LoadOneClickPartialPage(this.href); return false;'>Edit</a>
                                |
                                @{ var tt = PeriodEntry.Where(x => x.CLASS_TIMING_ID == item.ID).ToList();}
                                @if (tt == null || tt.Count() == 0)
                                {
                                    @Html.ActionLink("Delete", "Destroy", new { id = item.ID }, new { @onclick = "return confirm('are you sure?')" })
                                }
                                else
                                {
                                    <s>Delete</s>
                                }
                            </small>
                        </td>
                    </tr>
                }
            </table>
        }
        else
        {
            <p class="flash-msg"> No class timings found </p>
        }
        <div id="modal-box" style="display:none;"></div>
        <div class="extender"></div>
        <div class="LoaderBox" hidden="hidden"><img src="~/Content/images/loader.gif" id="loader" alt="Finance Logo" style="align-self:center; border:none"></div>
    </div>

</div>

SFSAcademy/SFSAcademy/Views/Class_Timings/Index.cshtml
@model IEnumerable<SFSAcademy.CLASS_TIMING_SET>
@{
    ViewBag.Title = "Index";
}
<div id="content-header">
    <img src="~/Content/images/show_timetable.png" alt="Timetable Logo">
    <h1>Timetable</h1>
    <h3>Class Timing Sets</h3>
    <div id="app-back-button">
        <a href='javascript:history.back()' onclick="return confirm('are you sure?')"><img src="~/Content/images/buttons/back.png"></a>
    </div>
</div>
<div><img src="~/Content/images/_global/header_underline_.jpg" style="width:100%"></div>
<div id="inner-tab-menu">
    <ul>
        <li>@Html.ActionLink("New", "Class_TimingSet_New")</li>
    </ul>
</div>
<div class="bread_crumb">
    <a href="@Url.Action("Index", "Timetable")"> Timetable &raquo; </a> 
    Class Timings Set
</div>
<div id="page-yield">
    @if (ViewBag.Notice != null)
    {
        <p class="flash-msg"> @ViewBag.Notice </p>
    }
    <table id="class-timings-list" style="width:100%">
        <tr>
            <th>
                Sl. No.
            </th>
            <th>
                Name
            </th>
            <th>
                Options
            </th>
        </tr>
        @{int i = 1; }
        @foreach (var item in Model)
        {
            string selectedRow = "tr-even";
            if (i % 2 == 0)
            {
                selectedRow = "tr-odd";
            }
            <tr id="class-timing-@item.ID" class="@selectedRow">
                <td class="col-1">
                    @i
                </td>
                <td class="col-2">
                    @Html.DisplayFor(modelItem => item.NAME)
                </td>
                <td class="col-2">
                    @Html.ActionLink("View class timings", "Class_TimingSet_View", new { id = item.ID }) |
                    @Html.ActionLink("Delete", "Class_TimingSet_Delete", new { id = item.ID }, new { @onclick = "return confirm('are you sure you want to delete this?')" })
                </td>
            </tr>
            i = i + 1;
        }
    </table>
</div>

SFSAcademy/SFSAcademy/Views/Class_Timings/_Edit.cshtml
@model SFSAcademy.CLASS_TIMING_ENTRY

@{
    SFSAcademy.CLASS_TIMING_SET Class_Timing_Set = (SFSAcademy.CLASS_TIMING_SET)ViewData["Class_Timing_Set"];
}
<script type="text/javascript" language="javascript">
    $(document).ready(function () {
        $(function () {
            $("#modal-box").dialog({
                autoOpen: false,
                draggable: true,
                resizable: true,
                width: 500,
                height: 'auto',
                dialogClass: "alert",
                cache: false,
                buttons: {
                    Cancel: function () {
                        $("#modal-box").dialog("close");
                    }
                },
                modal: true
            });

        });

        // initialize input widgets first
        $('.timepicker').timepicker({
            'showDuration': true,
            'timeFormat': 'g:ia',
            'minTime': '7:00am',
            'maxTime': '8:00pm',
            'step': 5,
            'timeFormat': 'H:i:s'
        });

        // initialize datepair
        var basicExampleEl = document.getElementById('timepicker');
        var basicExampleEl2 = document.getElementById('timepicker2');
    });
    $('#modal-box').dialog("open");
</script>

<label class="head_label">
    Edit class timing for @Model.CLASS_TIMING_SET.NAME

</label>
<div id="ajax-edit">
    @using (Html.BeginForm("Update", "Class_Timings", FormMethod.Post, new { @encType = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.ID)
        @Html.Hidden("CLASS_TIMING_SET_ID", Class_Timing_Set.ID)
        <div id="form-errors"></div>
        <div class="label-field-pair label">
            <label for="name">Name</label>
            <div class="text-input-bg">@Html.EditorFor(model => model.NAME)</div>
        </div>

        <div class="label-field-pair label">
            <label for="name"> Start Time </label>
            <div class="time-select-field">
                @Html.EditorFor(model => model.START_TIME, new { htmlAttributes = new { @class = @"timepicker", @id = "timepicker" } })
            </div>
        </div>
        <div class="label-field-pair label">
            <label for="name">End Time</label>
            <div class="time-select-field">
                @Html.EditorFor(model => model.END_TIME, new { htmlAttributes = new { @class = @"timepicker", @id = "timepicker2" } })
            </div>
        </div>
        <div class="label-checkbox-pair label">
            @if (Model.IS_BRK)
            {
                <label>@Html.CheckBoxFor(x => x.IS_BRK, new { @checked = true }) Is a break</label>
            }
            else
            {
                <label>@Html.CheckBoxFor(x => x.IS_BRK, new { @checked = false }) Is a break</label>
            }
        </div>
        <input type="submit" value="► Save" class="user_button" />
    }
</div>

SFSAcademy/SFSAcademy/Views/Class_Timings/_New.cshtml
@model SFSAcademy.CLASS_TIMING_ENTRY
@{
    SFSAcademy.CLASS_TIMING_SET Class_Timing_Set = (SFSAcademy.CLASS_TIMING_SET)ViewData["Class_Timing_Set"];
}
@{
    ViewBag.Title = "New";
}

<script type="text/javascript" language="javascript">
    $(document).ready(function () {
        $(function () {
            $("#modal-box").dialog({
                autoOpen: false,
                draggable: true,
                resizable: true,
                width: 500,
                height: 'auto',
                dialogClass: "alert",
                cache: false,
                buttons: {
                    Cancel: function () {
                        $("#modal-box").dialog("close");
                    }
                },
                modal: true
            });

        });

        // initialize input widgets first
        $('.timepicker').timepicker({
            'showDuration': true,
            'timeFormat': 'g:ia',
            'minTime': '7:00am',
            'maxTime': '8:00pm',
            'step': 5,
            'timeFormat': 'H:i:s'
        });

        // initialize datepair
        var basicExampleEl = document.getElementById('timepicker');
        var basicExampleEl2 = document.getElementById('timepicker2');
    });
    $('#modal-box').dialog("open");
</script>

<label class="head_label">
    Add New class timing for @Class_Timing_Set.NAME
</label>
<div id="ajax-create">
    @using (Html.BeginForm("Create", "Class_Timings", FormMethod.Post, new { @encType = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        @Html.Hidden("CLASS_TIMING_SET_ID", Class_Timing_Set.ID)
        <div id="form-errors"></div>
        <div class="label-field-pair label">
            <label for="name">Name</label>
            <div class="text-input-bg">@Html.EditorFor(model => model.NAME)</div>
        </div>

        <div class="label-field-pair label">
            <label for="name"> Start Time </label>
            <div class="time-select-field">
                @Html.EditorFor(model => model.START_TIME, new { htmlAttributes = new { @class = @"timepicker", @id = "timepicker" } })
            </div>
        </div>
        <div class="label-field-pair label">
            <label for="name">End Time</label>
            <div class="time-select-field">
                @Html.EditorFor(model => model.END_TIME, new { htmlAttributes = new { @class = @"timepicker", @id = "timepicker2" } })
            </div>
        </div>
        <div class="label-checkbox-pair label">
            <label>@Html.CheckBoxFor(x => x.IS_BRK) Is a break</label>
        </div>
        <input type="submit" value="► Save" class="user_button" />

    }
</div>