SFSAcademy/SFSAcademy/Models/Timetable.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;


namespace SFSAcademy
{
    public class WeekdaysSelect
    {
        public string Day { get; set; }
        public int Id { set; get; }
        public bool Select { get; set; }
        public string ClassTimingSet { get; set; }
    }

    public class Weekdays
    {
        public int DayId { get; set; }
        public List<WeekdaysSelect> WeekdayIds { get; set; }
        //Other Properties also her

        public Weekdays()
        {
            WeekdayIds = new List<WeekdaysSelect>();
        }

    }

    public class BatchWeekdaysSelect
    {
        public string Day { get; set; }
        public int Id { set; get; }
        public bool Select { get; set; }
        public string ClassTimingSet { get; set; }
    }

    public class EmployeeWorkAllotment
    {
        public EMPLOYEE EmployeeData { get; set; }
        public EMPLOYEE_DEPARTMENT DepartmentData { get; set; }
        public decimal? Total_Time { get; set; }
    }

    public class ClassTimings
    {
        public string NAME { get; set; }
        [Required(ErrorMessage = "Start Time is required")]
        [DataType(DataType.Time)]
        [DisplayFormat(DataFormatString = "{0:hh\\:mm}")]
        public Nullable<System.TimeSpan> StartTimeVal { get; set; }

        [DisplayFormat(DataFormatString = "{0:hh\\:mm tt}")]
        public DateTime? START_TIME { get { return (StartTimeVal.HasValue) ? (DateTime?)DateTime.Today.Add(StartTimeVal.Value) : null; } }

        [Required(ErrorMessage = "End Time is required")]
        [DataType(DataType.Time)]
        [DisplayFormat(DataFormatString = "{0:hh\\:mm}")]
        public Nullable<System.TimeSpan> EndTimeVal { get; set; }

        [DisplayFormat(DataFormatString = "{0:hh\\:mm tt}")]
        public DateTime? END_TIME { get { return (EndTimeVal.HasValue) ? (DateTime?)DateTime.Today.Add(EndTimeVal.Value) : null; } }

        public bool IS_BRK { get; set; }
    }

    public partial class TIMETABLE
    {
        private SFSAcademyEntities db = new SFSAcademyEntities();

        public List<DateTime> Register_Range(BATCH batch, DateTime date)
        {
            List<DateTime> start = new List<DateTime>();
            start.Add((DateTime)batch.START_DATE);
            DateTime BeginDate = new DateTime(date.Year, date.Month, 1);
            start.Add(BeginDate);
            DateTime ttSTartDate = (DateTime)db.TIMETABLEs.Select(x => x.START_DATE).ToList().Min();
            start.Add(ttSTartDate);

            List<DateTime> stop = new List<DateTime>();
            stop.Add((DateTime)batch.END_DATE);
            DateTime EndDate = BeginDate.AddMonths(1).AddDays(-1);
            stop.Add(EndDate);
            DateTime ttEndDate = (DateTime)db.TIMETABLEs.Select(x => x.END_DATE).ToList().Max();
            stop.Add(ttEndDate);

            List<DateTime> holidays = batch.Holiday_Event_Dates();
            DateTime MaxDate = (DateTime)start.Max();
            DateTime MinDate = (DateTime)stop.Min();

            List<DateTime> range = new List<DateTime>();
            for (var dt = MaxDate; dt <= MinDate; dt = dt.AddDays(1))
            {
                bool Select = true;
                foreach (var hld in holidays)
                {
                    if (dt == hld.Date)
                    {
                        Select = false;
                        break; ;
                    }
                }
                if (Select == true)
                {
                    range.Add(dt);
                }
            }
            return range;
        }
        public IEnumerable<TIMETABLE_ENTRY> tte_for_the_day(BATCH batch, DateTime? date)
        {
            var entries = db.TIMETABLE_ENTRY.Include(x => x.TIMETABLE).Include(x => x.CLASS_TIMING).Include(x => x.WEEKDAY).Include(x => x.SUBJECT).Include(x => x.SUBJECT.ELECTIVE_GROUP).Include(x => x.EMPLOYEE).Where(x => x.TIMETABLE.START_DATE <= date && x.TIMETABLE.END_DATE >= date && x.BTCH_ID == batch.ID).OrderBy(x => x.CLASS_TIMING.START_TIME).ToList();
            var today = db.TIMETABLE_ENTRY.Where(x => x.ID == -1).ToList().DefaultIfEmpty();
            if(entries != null || entries.Count() != 0)
            {
                today = entries.Where(x => x.WEEKDAY.DAY_OF_WK == (int)date.Value.DayOfWeek).ToList();
            }
            return (IEnumerable<TIMETABLE_ENTRY>)today;
        }

        //this is Partially done as currently Timetable Entries in our system is not stored at day level so removing holidays from the list needs to be implemented later on.
        public List<DateTime> tte_for_range(BATCH batch, DateTime date, SUBJECT subject)
        {
            if(subject.ELECTIVE_GRP_ID != null)
            {
                subject = subject.ELECTIVE_GROUP.SUBJECTs.FirstOrDefault();
            }
            var range = Register_Range(batch, date);
            DateTime? RangeFirst = range.First();
            DateTime? RangeLast = range.Last();
            var holidays = batch.Holiday_Event_Dates();

            var entries = db.TIMETABLE_ENTRY.Include(x => x.TIMETABLE).Include(x => x.CLASS_TIMING).Include(x => x.WEEKDAY).Include(x => x.SUBJECT).Include(x => x.SUBJECT.ELECTIVE_GROUP).Include(x => x.EMPLOYEE).Where(x => ((x.TIMETABLE.START_DATE <= RangeFirst && x.TIMETABLE.END_DATE >= RangeFirst) || (x.TIMETABLE.START_DATE <= RangeLast && x.TIMETABLE.END_DATE >= RangeLast) || (RangeFirst <= x.TIMETABLE.START_DATE && RangeLast >= x.TIMETABLE.START_DATE) || (RangeFirst <= x.TIMETABLE.END_DATE && RangeLast >= x.TIMETABLE.END_DATE)) && x.SUBJ_ID == subject.ID && x.BTCH_ID == batch.ID && x.CLASS_TIMING.IS_DEL == false && x.WEEKDAY.IS_DEL == false).OrderBy(x => x.TIMT_ID).ToList();
            List<int?> timetable_ids = new List<int?>();
            timetable_ids = entries.Select(x => x.TIMT_ID).Distinct().ToList();
            var timetables = db.TIMETABLEs.Where(x => timetable_ids.Contains(x.ID)).ToList();
            List<DateTime> hsh2 = new List<DateTime>();
            foreach (var tt in timetables)
            {
                List<DateTime> MaxDate = new List<DateTime>();
                MaxDate.Add((DateTime)tt.START_DATE);
                MaxDate.Add((DateTime)range.First());

                List<DateTime> MinDate = new List<DateTime>();
                MinDate.Add((DateTime)tt.END_DATE);
                MinDate.Add((DateTime)range.Last());

                for (var dt = MaxDate.Max(); dt <= MinDate.Min(); dt = dt.AddDays(1))
                {
                    bool Select = false;
                    foreach (var WkD in entries.Where(x=>x.TIMT_ID == tt.ID))
                    {
                        if ((int)dt.DayOfWeek == WkD.WEEKDAY.DAY_OF_WK)
                        {
                            Select = true;
                            break; ;
                        }
                    }
                    foreach (var hld in holidays)
                    {
                        if (dt == hld.Date)
                        {
                            Select = false;
                            break; ;
                        }
                    }
                    if (Select == true)
                    {
                        hsh2.Add(dt);
                    }
                }
            }
            return hsh2;
        }
    }

}

SFSAcademy/SFSAcademy/Controllers/TimetableController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SFSAcademy;

namespace SFSAcademy.Controllers
{
    public class TimetableController : Controller
    {
        private SFSAcademyEntities db = new SFSAcademyEntities();

        // GET: Timetable
        public ActionResult Index(string ErrorMessage, string Notice)
        {
            ViewBag.ErrorMessage = ErrorMessage;
            ViewBag.Notice = Notice;
            var config = db.CONFIGURATIONs.Where(x => x.CONFIG_KEY == "AvailableModules").ToList();
            ViewData["config"] = config;
            ViewBag.StudentAttendanceType = db.CONFIGURATIONs.Where(x => x.CONFIG_KEY == "StudentAttendanceType").Select(x => x.CONFIG_VAL).FirstOrDefault().ToString();
            return View();
        }

        // GET: Timetable/Create
        public ActionResult Work_Allotment(string Notice, string ErrorMessage)
        {
            ViewBag.Notice = Notice;
            ViewBag.ErrorMessage = ErrorMessage;
            var admin = db.EMPLOYEE_CATEGORY.Where(x => !x.PRFX.Contains("admin")).ToList();
            ViewData["admin"] = admin;

            var employees = (from emp in db.EMPLOYEEs.Include(x=>x.EMPLOYEE_GRADE).Include(x=>x.EMPLOYEES_SUBJECT).Include(x=>x.EMPLOYEE_DEPARTMENT)
                             join empcat in db.EMPLOYEE_CATEGORY on emp.EMP_CAT_ID equals empcat.ID
                             where !empcat.PRFX.Contains("admin")
                              select new EmployeeWorkAllotment { EmployeeData = emp, Total_Time = emp.EMPLOYEE_GRADE.MAX_WKILY_HRS}).ToList();
            ViewData["employees"] = employees;

            DateTime StartDate = HtmlHelpers.ApplicationHelper.AcademicYearStartDate();
            var batches = (from cs in db.COURSEs
                           join bt in db.BATCHes.Include(x => x.SUBJECTs.Select(c => c.EMPLOYEES_SUBJECT)) on cs.ID equals bt.CRS_ID
                           where bt.END_DATE >= StartDate
                           select new SFSAcademy.CoursesBatch { BatchData = bt, CourseData = cs, Total_Time = 0 }).Distinct().ToList();
            ViewData["batches"] = batches;

            return View();
        }

        public ActionResult Manage_Allotment(int? batch_id, int? sub_id, string Notice, string ErrorMessage)
        {
            ViewBag.Notice = Notice;
            ViewBag.ErrorMessage = ErrorMessage;
            DateTime StartDate = HtmlHelpers.ApplicationHelper.AcademicYearStartDate();
            var queryCourceBatch = (from cs in db.COURSEs
                                    join bt in db.BATCHes on cs.ID equals bt.CRS_ID
                                    where cs.IS_DEL == false && bt.END_DATE >= StartDate
                                    select new CoursesBatch { CourseData = cs, BatchData = bt })
                        .OrderBy(x => x.BatchData.ID).ToList();


            List<SelectListItem> options = new List<SelectListItem>();
            foreach (var item in queryCourceBatch)
            {
                string BatchFullName = string.Concat(item.CourseData.CODE, "-", item.BatchData.NAME);
                var result = new SelectListItem();
                result.Text = BatchFullName;
                result.Value = item.BatchData.ID.ToString();
                result.Selected = item.BatchData.ID == batch_id? true: false;
                options.Add(result);
            }
            // add the 'ALL' option
            options.Insert(0, new SelectListItem() { Value = "-1", Text = "Select Batch" });
            ViewBag.BTCH_ID = options;
            BATCH batch = db.BATCHes.Include(x => x.COURSE).Where(x => x.ID == batch_id).FirstOrDefault();
            ViewData["batch"] = batch;

            List<SelectListItem> options2 = new SelectList(db.SUBJECTs.Where(x => x.BTCH_ID == batch_id && x.IS_DEL == false).OrderBy(c => c.NAME), "ID", "NAME", sub_id).ToList();
            // add the 'ALL' option
            options2.Insert(0, new SelectListItem() { Value = "-1", Text = "Select a Subject" });
            ViewBag.SUB_ID = options2;

            SUBJECT subject = db.SUBJECTs.Find(sub_id);
            ViewData["subject"] = subject;
            var assigned_employee = db.EMPLOYEES_SUBJECT.Where(x => x.SUBJ_ID == sub_id).ToList();
            ViewData["assigned_employee"] = assigned_employee;
            var departments = db.EMPLOYEE_DEPARTMENT.Where(x => x.STAT == true).ToList();
            ViewData["departments"] = departments;
            var Employee = db.EMPLOYEEs.ToList();
            ViewData["Employee"] = Employee;
            List<SelectListItem> options3 = new SelectList(db.EMPLOYEE_DEPARTMENT.Where(x => x.STAT == true).OrderBy(c => c.NAMES), "ID", "NAMES").ToList();
            // add the 'ALL' option
            options3.Insert(0, new SelectListItem() { Value = "-1", Text = "Select a Department" });
            ViewBag.DEPT_ID = options3;

            return View();
        }

        public ActionResult Subject_Select(int? batch_id)
        {
            BATCH batch = db.BATCHes.Include(x => x.COURSE).Where(x => x.ID == batch_id).FirstOrDefault();
            ViewData["batch"] = batch;
            List<SelectListItem> options = new SelectList(db.SUBJECTs.Where(x => x.BTCH_ID == batch_id && x.IS_DEL == false).OrderBy(c => c.NAME), "ID", "NAME").ToList();
            // add the 'ALL' option
            options.Insert(0, new SelectListItem() { Value = "-1", Text = "Select a Subject" });
            ViewBag.SUB_ID = options;

            return PartialView("_Subject_Select");
        }

        public ActionResult Department_Select(int? subject_id, int? batch_id)
        {
            SUBJECT subject = db.SUBJECTs.Find(subject_id);
            ViewData["subject"] = subject;
            var assigned_employee = db.EMPLOYEES_SUBJECT.Where(x => x.SUBJ_ID == subject_id).ToList();
            ViewData["assigned_employee"] = assigned_employee;
            var departments = db.EMPLOYEE_DEPARTMENT.Where(x => x.STAT == true).ToList();
            ViewData["departments"] = departments;
            var Employee = db.EMPLOYEEs.ToList();
            ViewData["Employee"] = Employee;
            BATCH batch = db.BATCHes.Include(x => x.COURSE).Where(x => x.ID == batch_id).FirstOrDefault();
            ViewData["batch"] = batch;
            List<SelectListItem> options = new SelectList(db.EMPLOYEE_DEPARTMENT.Where(x => x.STAT == true).OrderBy(c => c.NAMES), "ID", "NAMES").ToList();
            // add the 'ALL' option
            options.Insert(0, new SelectListItem() { Value = "-1", Text = "Select a Department" });
            ViewBag.DEPT_ID = options;

            return PartialView("_Department_Select");
        }

        public ActionResult Update_Employees(int? department_id, int? subject_id, int? batch_id)
        {
            SUBJECT subject = db.SUBJECTs.Find(subject_id);
            ViewData["subject"] = subject;
            var employees = db.EMPLOYEEs.Where(x => x.EMP_DEPT_ID == department_id && x.STAT == true).ToList();
            ViewData["employees"] = employees;
            var EmployeesSubject = db.EMPLOYEES_SUBJECT.ToList();
            ViewData["EmployeesSubject"] = EmployeesSubject;
            BATCH batch = db.BATCHes.Include(x => x.COURSE).Where(x => x.ID == batch_id).FirstOrDefault();
            ViewData["batch"] = batch;
            return PartialView("_Employee_List");
        }

        public ActionResult Assign_Employee(int? id, int? id1, int? batch_id)
        {
            var departments = db.EMPLOYEE_DEPARTMENT.Where(x => x.STAT == true).ToList();
            ViewData["departments"] = departments;
            SUBJECT subject = db.SUBJECTs.Find(id1);
            ViewData["subject"] = subject;
            var employee_department_id = db.EMPLOYEEs.Find(id).EMP_DEPT_ID;
            var employees = db.EMPLOYEEs.Where(x => x.EMP_DEPT_ID == employee_department_id && x.STAT == true).ToList();
            ViewData["employees"] = employees;
            EMPLOYEES_SUBJECT EmployeesSubject = new EMPLOYEES_SUBJECT { EMP_ID = id, SUBJ_ID = id1 };
            db.EMPLOYEES_SUBJECT.Add(EmployeesSubject);
            db.SaveChanges();
            var assigned_employee = db.EMPLOYEES_SUBJECT.Where(x => x.SUBJ_ID == subject.ID).ToList();
            ViewData["assigned_employee"] = assigned_employee;
            ViewBag.Notice = "Employee Successfully assigned.";
            return RedirectToAction("Manage_Allotment", new { batch_id = batch_id, sub_id = id1, Notice = ViewBag.Notice });
        }

        public ActionResult Remove_Employee(int? id, int? id1, int? batch_id)
        {
            var departments = db.EMPLOYEE_DEPARTMENT.Where(x => x.STAT == true).ToList();
            ViewData["departments"] = departments;
            SUBJECT subject = db.SUBJECTs.Find(id1);
            ViewData["subject"] = subject;
            var employee_department_id = db.EMPLOYEEs.Find(id).EMP_DEPT_ID;
            var employees = db.EMPLOYEEs.Where(x => x.EMP_DEPT_ID == employee_department_id && x.STAT == true).ToList();
            ViewData["employees"] = employees;
            var TimetableEntry = db.TIMETABLE_ENTRY.Include(x=>x.TIMETABLE).Where(x => x.SUBJ_ID == subject.ID && x.EMP_ID == id && x.TIMETABLE.END_DATE >= DateTime.Now).ToList();
            if (TimetableEntry == null || TimetableEntry.Count() == 0)
            {
                EMPLOYEES_SUBJECT EmployeesSubject = db.EMPLOYEES_SUBJECT.Where(x => x.EMP_ID == id && x.SUBJ_ID == id1).FirstOrDefault();
                db.EMPLOYEES_SUBJECT.Remove(EmployeesSubject);
                db.SaveChanges();
                ViewBag.Notice = "Employee sucessfully removed.";
            }
            else
            {

SFSAcademy/SFSAcademy/Views/Timetable/Manage_Allotment.cshtml
@{
    ViewBag.Title = "Manage_Allotment";
}
<script type="text/javascript" src="@Url.Content("~/Content/javascripts/jquery/jquery.min.js")"></script>
<script type="text/javascript" src="@Url.Content("~/Content/javascripts/jquery/jquery-ui.min.js")"></script>
<script type="text/javascript" src="@Url.Content("~/Content/javascripts/jquery/jquery-1.9.1.js")"></script>
<script type="text/javascript" src="@Url.Content("~/Content/javascripts/jquery/jquery-ui.js")"></script>
<link rel="stylesheet" href="~/Content/stylesheets/_styles/jquery-ui.css" />
<script type="text/javascript" language="javascript">
    /* This is change event for your dropdownlist */
    $(document.forms[0]).ready(function () {
        $(".LoaderBox").hide();
        $('#BatchDropDown').change(function () {
            var selectedID = $(this).val();
            $(".LoaderBox").show();
            $.get('/Timetable/Subject_Select?batch_id=' + selectedID, function (data) {
                $('#subjects_select').html(data);
                $('#subjects_select').fadeIn('fast');
            }).success(function (status) {
                $(".LoaderBox").hide();
            });

        });
    });
</script>
<div id="content-header">
    <img src="~/Content/images/show_timetable.png" alt="Timetable Logo">
    <h1>Timetable</h1>
    <h3>Manage Allotment</h3>
    <div id="app-back-button">
        <a href='javascript:history.back()' onclick="return confirm('are you sure?')"><img src="~/Content/images/buttons/back.png"></a>
    </div>
</div>
<div><img src="~/Content/images/_global/header_underline_.jpg" style="width:100%"></div>

<div id="inner-tab-menu">
    <ul>
        <li><a href="@Url.Action("Work_Allotment", "Timetable")">Work Allotment</a></li>
    </ul>
</div>
@if (ViewBag.Notice != null)
{
    <div id="errorExplanation" class="errorExplanation">@ViewBag.Notice </div>
}
<div id="page-yield">
    <div class="form-content">
        <div class="label-field-pair label">
            <div class="label-container label">@Html.Label("BTCH_ID", "Select A Batch :", htmlAttributes: new { @class = "control-label col-md-2" })</div>
            <div class="text-input-bg">
                @Html.DropDownList("BTCH_ID", null, htmlAttributes: new { @class = "form-control", @id = "BatchDropDown" })
                <div class="LoaderBox"><img src="~/Content/images/loader.gif" id="loader" alt="Finance Logo" style="align-self:center; border:none"></div>
                @Html.ValidationMessage("BTCH_ID", "", new { @class = "text-danger" })
            </div>
        </div>
        <div id="subjects_select">@Html.Partial("_Subject_Select")</div>
    </div>
    <div id="department-select">@Html.Partial("_Department_Select")</div>
</div>

SFSAcademy/SFSAcademy/Views/Timetable/Teachers_Timetable.cshtml
@{
    TIMETABLE current = (TIMETABLE)ViewData["current"];
}
@{
    ViewBag.Title = "Teachers_Timetable";
}
<script type="text/javascript" src="@Url.Content("~/Content/javascripts/jquery/jquery.min.js")"></script>
<script type="text/javascript" src="@Url.Content("~/Content/javascripts/jquery/jquery-ui.min.js")"></script>
<script type="text/javascript" src="@Url.Content("~/Content/javascripts/jquery/jquery-1.9.1.js")"></script>
<script type="text/javascript" src="@Url.Content("~/Content/javascripts/jquery/jquery-ui.js")"></script>

<script type="text/javascript" src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.min.js")"></script>
<script type="text/javascript" src="@Url.Content("~/Scripts/jquery.validate.min.js")"></script>
<script type="text/javascript" src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")"></script>
<link rel="stylesheet" href="~/Content/stylesheets/_styles/jquery.ui.all.css" />
<link rel="stylesheet" href="~/Content/stylesheets/_styles/jquery-ui.css" />
<script type="text/javascript">
    $(document).ready(function () {
        $(".LoaderBox").hide();
        var SelectedTTId = $('#timetable_id').val();
        $.get('/Timetable/Update_Teacher_TT?timetable_id=' + SelectedTTId, function (data) {
            $('#timetable_view').html(data);
            $('#timetable_view').fadeIn('fast');
        }).success(function (status) {
            $(".LoaderBox").hide();
        });
    });
    function show_timetable() {
        $(".LoaderBox").show();
        var SelectedTTId = $('#TiemtableDropDown').val();
        $.get('/Timetable/Update_Teacher_TT?timetable_id=' + SelectedTTId, function (data) {
            $('#timetable_view').html(data);
            $('#timetable_view').fadeIn('fast');
        }).success(function (status) {
            $(".LoaderBox").hide();
        });
    }
</script>
<div id="content-header">
    <img src="~/Content/images/show_timetable.png" alt="Timetable Logo">
    <h1>Timetable</h1>
    <h3>Teacher Timetable</h3>
    <div id="app-back-button">
        <a href='javascript:history.back()' onclick="return confirm('are you sure?')"><img src="~/Content/images/buttons/back.png"></a>
    </div>
</div>
<div><img src="~/Content/images/_global/header_underline_.jpg" style="width:100%"></div>
<div class="bread_crumb">
    <a href="@Url.Action("Index", "Timetable")"> Timetable</a> &raquo;
    Teacher's Timetable
</div>
<div id="page-yield">
    @if (ViewBag.Notice != null)
    {
        <p class="flash-msg"> @ViewBag.Notice </p>
    }
    @using (Html.BeginForm())
    {
        <div class="label-field-pair">
            <label for="timetable_entry_course_id">Select a timetable</label>
            <div class="text-input-bg">
                @Html.DropDownList("TIMT_ID", null, htmlAttributes: new { @class = "form-control", @id = "TiemtableDropDown", @onChange = "show_timetable()" })
                <div class="LoaderBox"><img src="~/Content/images/loader.gif" id="loader" alt="Finance Logo" style="align-self:center; border:none"></div>
            </div>
        </div>
    }


    <div id="timetable_view">
        @if (current != null)
        {
            @Html.Partial("_Teacher_Timetable")
        }

    </div>
</div>
<input type="hidden" value="@current.ID" id="timetable_id" name="timetable_id" />

SFSAcademy/SFSAcademy/Views/Timetable/_Department_Select.cshtml
@{
    SUBJECT subject = (SUBJECT)ViewData["subject"];
    BATCH batch = (BATCH)ViewData["batch"];
    IEnumerable<SFSAcademy.EMPLOYEES_SUBJECT> assigned_employee = (IEnumerable<SFSAcademy.EMPLOYEES_SUBJECT>)ViewData["assigned_employee"];
    IEnumerable<SFSAcademy.EMPLOYEE_DEPARTMENT> departments = (IEnumerable<SFSAcademy.EMPLOYEE_DEPARTMENT>)ViewData["departments"];
    IEnumerable<SFSAcademy.EMPLOYEE> Employee = (IEnumerable<SFSAcademy.EMPLOYEE>)ViewData["Employee"];
}
<script type="text/javascript" language="javascript">
    $(document.forms[0]).ready(function () {
        $(".LoaderBox").hide();
        $('#DepartmentDropDown').change(function () {
            var selectedID = $(this).val();
            var SelectedSub = $('#subject_id').val();
            var SelectedBatch = $('#batch_id').val();
            $(".LoaderBox").show();
            $.get('/Timetable/Update_Employees?department_id=' + selectedID + "&subject_id=" + SelectedSub + "&batch_id=" + SelectedBatch, function (data) {

                /* data is the pure html returned from action method, load it to your page */
                $('#employee-list').html(data);
                /* little fade in effect */
                $('#employee-list').fadeIn('fast');
            }).success(function (status) {
                $(".LoaderBox").hide();
            });

        });
    });
</script>
<ul id="department-list">
    @if (assigned_employee != null && assigned_employee.Count() != 0)
    {
        <li class="heading">Currently Assigned: </li>
        int i = 0;
        foreach (var item in assigned_employee)
        {
            var employee = Employee.Where(x => x.ID == item.EMP_ID).FirstOrDefault();
            string selectedRow = "listeven";
            if (i % 2 == 0)
            {
                selectedRow = "listodd";
            }
            <li class="@selectedRow">
                <div class="department-name">
                    @employee.FIRST_NAME @employee.LAST_NAME ( DEPT: @departments.Where(x => x.ID == employee.EMP_DEPT_ID).FirstOrDefault().NAMES )
                </div>
                <div class="remove">
                    <a href="@Url.Action("Remove_Employee", "Timetable",new {id=item.EMP_ID, id1 =item.SUBJ_ID, batch_id = batch.ID })">Delete</a>
                </div>
            </li>
        }
    }
    else
    {
        <p class="flash-msg">No Employee Assigned</p>
    }
</ul>
<div class="label-field-pair label">
    <div class="label-container label">@Html.Label("DEPT_ID", "Select A Department :", htmlAttributes: new { @class = "control-label col-md-2" })</div>
    <div class="text-input-bg">
        @Html.DropDownList("DEPT_ID", null, htmlAttributes: new { @class = "form-control", @id = "DepartmentDropDown" })        
        @Html.ValidationMessage("DEPT_ID", "", new { @class = "text-danger" })
    </div>
</div>
<div id="employee-list" style="display:none;"></div>
<div class="extender"></div>
<input type="hidden" value="@subject.ID" id="subject_id" name="subject_id" />
<input type="hidden" value="@batch.ID" id="batch_id" name="batch_id" />