SFSAcademy/SFSAcademy/Controllers/Employee_AttendanceController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SFSAcademy;
using System.Data.Entity.Validation;


namespace SFSAcademy.Controllers
{
    public class Employee_AttendanceController : Controller
    {
        private SFSAcademyEntities db = new SFSAcademyEntities();

        // GET: Employee_Attendance
        public ActionResult Index()
        {
            var eMPLOYEE_ATTENDENCES = db.EMPLOYEE_ATTENDENCES.Include(e => e.EMPLOYEE_LEAVE_TYPE).Include(e => e.EMPLOYEE);
            return View(eMPLOYEE_ATTENDENCES.ToList());
        }

        // GET: Employee_Attendance/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EMPLOYEE_ATTENDENCES eMPLOYEE_ATTENDENCES = db.EMPLOYEE_ATTENDENCES.Find(id);
            if (eMPLOYEE_ATTENDENCES == null)
            {
                return HttpNotFound();
            }
            return View(eMPLOYEE_ATTENDENCES);
        }

        // GET: Employee_Attendance/Create
        public ActionResult Add_Leave_Types(string ErrorMessage, string Notice)
        {
            var leave_types = db.EMPLOYEE_LEAVE_TYPE.Where(x => x.STAT == true).OrderBy(x => x.NAME).ToList();
            ViewData["leave_types"] = leave_types;
            var inactive_leave_types = db.EMPLOYEE_LEAVE_TYPE.Where(x => x.STAT == false).OrderBy(x => x.NAME).ToList();
            ViewData["inactive_leave_types"] = inactive_leave_types;
            ViewBag.ErrorMessage = ErrorMessage;
            ViewBag.Notice = Notice;
            return View();
        }

        // POST: Employee_Attendance/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add_Leave_Types([Bind(Include = "ID,NAME,CODE,STAT,MAX_LEAVE_CNT,CARR_FRWD")] EMPLOYEE_LEAVE_TYPE eMPLOYEE_lEAVE_tYPE)
        {
            var leave_types = db.EMPLOYEE_LEAVE_TYPE.Where(x => x.STAT == true).OrderBy(x => x.NAME).ToList();
            ViewData["leave_types"] = leave_types;
            var inactive_leave_types = db.EMPLOYEE_LEAVE_TYPE.Where(x => x.STAT == false).OrderBy(x => x.NAME).ToList();
            ViewData["inactive_leave_types"] = inactive_leave_types;
            if (ModelState.IsValid)
            {
                db.EMPLOYEE_LEAVE_TYPE.Add(eMPLOYEE_lEAVE_tYPE);
                foreach(var item in db.EMPLOYEEs.ToList())
                {
                    var EmployeeLeave = new EMPLOYEE_LEAVE() { EMP_ID = item.ID, EMP_LEAVE_TYPE_ID = eMPLOYEE_lEAVE_tYPE.ID, LEAVE_CNT = eMPLOYEE_lEAVE_tYPE.MAX_LEAVE_CNT, CREATED_AT = System.DateTime.Now, UPDATED_AT = System.DateTime.Now };
                    db.EMPLOYEE_LEAVE.Add(EmployeeLeave);
                }
                try { db.SaveChanges(); }
                catch (DbEntityValidationException e)
                {
                    foreach (var eve in e.EntityValidationErrors) { foreach (var ve in eve.ValidationErrors) { ViewBag.ErrorMessage = string.Concat(ViewBag.ErrorMessage, "|", ve.ErrorMessage); } }
                    return View();
                }
                catch (Exception e)
                {
                    ViewBag.ErrorMessage = string.Concat(ViewBag.ErrorMessage, "|", string.Concat(e.GetType().FullName, ":", e.Message));
                    return View();
                }
                ViewBag.Notice = "Leave Type added successfully!!";
                return RedirectToAction("Add_Leave_Types", new { ErrorMessage = ViewBag.ErrorMessage, Notice = ViewBag.Notice });
            }
            ViewBag.ErrorMessage = "Model State is not Valid";
            return View();
        }

        // GET: Employee_Attendance/Edit/5
        public ActionResult Edit_Leave_Types(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EMPLOYEE_LEAVE_TYPE leave_type = db.EMPLOYEE_LEAVE_TYPE.Find(id);
            if (leave_type == null)
            {
                return HttpNotFound();
            }
            return View(leave_type);
        }

        // POST: Employee_Attendance/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit_Leave_Types([Bind(Include = "ID,NAME,CODE,STAT,MAX_LEAVE_CNT,CARR_FRWD")] EMPLOYEE_LEAVE_TYPE eMPLOYEE_lEAVE_tYPE)
        {
            var leave_types = db.EMPLOYEE_LEAVE_TYPE.Where(x => x.STAT == true).OrderBy(x => x.NAME).ToList();
            ViewData["leave_types"] = leave_types;
            var inactive_leave_types = db.EMPLOYEE_LEAVE_TYPE.Where(x => x.STAT == false).OrderBy(x => x.NAME).ToList();
            ViewData["inactive_leave_types"] = inactive_leave_types;
            if (ModelState.IsValid)
            {
                EMPLOYEE_LEAVE_TYPE eMPLOYEE_lEAVE_tYPE_upd = db.EMPLOYEE_LEAVE_TYPE.Find(eMPLOYEE_lEAVE_tYPE.ID);
                eMPLOYEE_lEAVE_tYPE_upd.NAME = eMPLOYEE_lEAVE_tYPE.NAME;
                eMPLOYEE_lEAVE_tYPE_upd.CODE = eMPLOYEE_lEAVE_tYPE.CODE;
                eMPLOYEE_lEAVE_tYPE_upd.STAT = eMPLOYEE_lEAVE_tYPE.STAT;
                eMPLOYEE_lEAVE_tYPE_upd.MAX_LEAVE_CNT = eMPLOYEE_lEAVE_tYPE.MAX_LEAVE_CNT;
                eMPLOYEE_lEAVE_tYPE_upd.CARR_FRWD = eMPLOYEE_lEAVE_tYPE.CARR_FRWD;

                db.Entry(eMPLOYEE_lEAVE_tYPE_upd).State = EntityState.Modified;
                try { db.SaveChanges(); }
                catch (DbEntityValidationException e)
                {
                    foreach (var eve in e.EntityValidationErrors) { foreach (var ve in eve.ValidationErrors) { ViewBag.ErrorMessage = string.Concat(ViewBag.ErrorMessage, "|", ve.ErrorMessage); } }
                    return View();
                }
                catch (Exception e)
                {
                    ViewBag.ErrorMessage = string.Concat(ViewBag.ErrorMessage, "|", string.Concat(e.GetType().FullName, ":", e.Message));
                    return View();
                }
                ViewBag.Notice = "Leave Type edited successfully!!";
                return RedirectToAction("Add_Leave_Types", new { ErrorMessage = ViewBag.ErrorMessage, Notice = ViewBag.Notice });
            }
            ViewBag.ErrorMessage = "Model State is not Valid";
            return View();
        }

        // GET: Employee_Attendance/Delete/5
        public ActionResult Delete_Leave_Types(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EMPLOYEE_LEAVE_TYPE leave_type = db.EMPLOYEE_LEAVE_TYPE.Find(id);
            if (leave_type == null)
            {
                return HttpNotFound();
            }
            var attendance = db.EMPLOYEE_ATTENDENCES.Where(x => x.EMP_LEAVE_TYPE_ID == id).ToList();
            var leave_count = db.EMPLOYEE_LEAVE.Where(x => x.EMP_LEAVE_TYPE_ID == id).ToList();
            if(attendance == null || attendance.Count() == 0)
            {
                db.EMPLOYEE_LEAVE_TYPE.Remove(leave_type);
                foreach(var item in leave_count)
                {
                    EMPLOYEE_LEAVE Emp_Leave = db.EMPLOYEE_LEAVE.Find(item.ID);
                    db.EMPLOYEE_LEAVE.Remove(Emp_Leave);
                }
                ViewBag.Notice = "Leave type deleted succesfully";
            }
            else
            {
                ViewBag.Notice = "Leave Reset Successfull";
            }
            try { db.SaveChanges(); }
            catch (DbEntityValidationException e)
            {
                foreach (var eve in e.EntityValidationErrors) { foreach (var ve in eve.ValidationErrors) { ViewBag.ErrorMessage = string.Concat(ViewBag.ErrorMessage, "|", ve.ErrorMessage); } }
                return View();
            }
            catch (Exception e)
            {
                ViewBag.ErrorMessage = string.Concat(ViewBag.ErrorMessage, "|", string.Concat(e.GetType().FullName, ":", e.Message));
                return View();
            }
            return RedirectToAction("Add_Leave_Types", new { ErrorMessage = ViewBag.ErrorMessage, Notice = ViewBag.Notice });
        }

        public ActionResult Report(string ErrorMessage, string Notice)
        {
            ViewBag.ErrorMessage = ErrorMessage;
            ViewBag.Notice = Notice;
            List<SelectListItem> options = new SelectList(db.EMPLOYEE_DEPARTMENT.Where(x => x.STAT == true).OrderBy(x => x.NAMES), "ID", "NAMES").ToList();
            options.Insert(0, new SelectListItem() { Value = null, Text = "Select Department" });
            ViewBag.EMP_DEPT_ID = options;
            return View();
        }

        public ActionResult Update_Attendance_Report(int? department_id)
        {
            var leave_types = db.EMPLOYEE_LEAVE_TYPE.Where(x => x.STAT == true).ToList();
            ViewData["leave_types"] = leave_types;
            var employees = db.EMPLOYEEs.Where(x => x.EMP_DEPT_ID == department_id).ToList();
            ViewData["employees"] = employees;
            var EmployeeLeave = db.EMPLOYEE_LEAVE.ToList();
            ViewData["EmployeeLeave"] = EmployeeLeave;
            var EmployeeAttendance = db.EMPLOYEE_ATTENDENCES.ToList();
            ViewData["EmployeeAttendance"] = EmployeeAttendance;
            return PartialView("_Attendance_Report");
        }

        public ActionResult Emp_Attendance(int? id)
        {
            EMPLOYEE employee = db.EMPLOYEEs.Find(id);

SFSAcademy/SFSAcademy/Views/Employee/Change_Reporting_Manager.cshtml
@model IEnumerable<SFSAcademy.Employee>

@{
    IEnumerable<EMPLOYEE> Reporting_Manager = (IEnumerable<EMPLOYEE>)ViewData["Reporting_Manager"];
    EMPLOYEE Employee = (EMPLOYEE)ViewData["Employee"];
}
@{
    ViewBag.Title = "Admission4";
}

<div id="content-header">
    <img src="~/Content/images/HR/show_hr.png" alt="HR Logo">
    <h1>Reporting Manager</h1>
    <h3>Change</h3>
    <div id="app-back-button">
        <a href='javascript:history.back()' onclick="return confirm('are you sure?')"><img src="~/Content/images/buttons/back.png"></a>
    </div>
</div>
<div>
    <img src="~/Content/images/_global/header_underline_.jpg" style="width:100%">
</div>
<div id="page-yield">
    <div id="form-content">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <div id="current-changed-manager">
                Reporting Manager For: @Html.Label(string.Concat(Employee.FIRST_NAME, " ", Employee.MID_NAME, " ", Employee.LAST_NAME), htmlAttributes: new { @class = "control-label col-md-2" })
                @{
                    for (int i = 0; i < Reporting_Manager.Count(); i++)
                    {
                        <div class="label-field-pair label">
                            <div id="changed-manager-outer">
                                @if (Reporting_Manager.FirstOrDefault().LAST_NAME != null)
                                {
                                    <div id="changed-manager-name"> @Html.Label("Manager Name:") @Html.Label(Reporting_Manager.FirstOrDefault().FIRST_NAME) @Html.Label(Reporting_Manager.FirstOrDefault().LAST_NAME)</div>
                                }
                                else
                                {
                                    <div id="changed-manager-name">@Html.Label("Manager Name:") @Html.Label(Reporting_Manager.FirstOrDefault().FIRST_NAME)</div>
                                }
                                <div id="changed-manager-name">@Html.Label("Manager Employee Numer:")  @Html.Label(Reporting_Manager.FirstOrDefault().EMP_NUM)</div>
                                <div class="extender"></div>
                                <br />
                            </div>
                            <div class="text-input-bg">
                                @Html.Hidden("[" + i + "].Employee_Id", Employee.ID)
                                @Html.Hidden("[" + i + "].Reporting_Manager_Id", Reporting_Manager.ElementAt(i).ID)

                            </div>
                        </div>
                    }
                }
                <div id="update-button"><input type="submit" value="► Save And Proceed" class="submit_button" /></div>
            </div>
        }
        <div class="extender"></div>
        <br />
        <div id="search-options">
            @Html.Partial("~/Views/Employee/_Select_Reporting_Manager.cshtml")
        </div>
    </div>

    <div id="information"></div>
</div>

SFSAcademy/SFSAcademy/Views/Employee/Department_Payslip.cshtml
@{
    ViewBag.Title = "Department_Payslip";
}
<div id="content-header">
    <img src="~/Content/images/HR/show_hr.png" alt="HR Logo">
    <h1>Employee</h1>
    <h3>Department Wise Payslip</h3>
    <div id="app-back-button">
        <a href='javascript:history.back()' onclick="return confirm('are you sure?')"><img src="~/Content/images/buttons/back.png"></a>
    </div>
</div>
<div><img src="~/Content/images/_global/header_underline_.jpg" style="width:100%"></div>

<div id="page-yield">
    <div class="bread_crumb">
        @Html.ActionLink("HR", "HR") &raquo;
        Employee Payslip
    </div>
    @if (ViewBag.Notice != null)
            {
        <p class="flash-msg"> @ViewBag.Notice </p>
    }
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div id="box">
            <div class="label-field-pair label">
                <label for="student_course">Select Department:</label>
                <div class="text-input-bg">
                    @Html.DropDownList("departments", null, htmlAttributes: new { @class = "form-control", @id = "DepDropDown" })
                </div>
            </div>
            <div class="label-field-pair label">
                <label for="student_course">Select Month:</label>
                <div class="text-input-bg">
                    @Html.DropDownList("Salary_Date", null, htmlAttributes: new { @class = "form-control", @id = "SalDropDown" })
                </div>
            </div>
            <input type="submit" value="► View" class="submit_button" />
        </div>
    }

    <div id="payslip">
        @if (ViewBag.IsPost == true)
        {
            IEnumerable<SFSAcademy.Payslip> payslips = (IEnumerable<SFSAcademy.Payslip>)ViewData["payslips"];
            if (payslips != null && payslips.Count() != 0)
            {
                <table id="listing" style="width:100%">
                    <tr class="tr-head">
                        <td>Sl No</td>
                        <td>Employee</td>
                        <td>Employee No.</td>
                        <td>Net Salary</td>
                        <td>Payslip Status</td>
                        <td></td>
                    </tr>
                    @{ decimal? total_salary = 0; decimal? total_approved_salary = 0; decimal? total_employees = 0; int i = 0;}

                    @if (payslips.FirstOrDefault().Monthy_Payslip_Amount != null)
                    {
                        foreach (var item in payslips)
                        {
                            string selectedRow = "tr-even";
                            total_salary += (decimal)item.Net_Amount;
                            if (item.Aapproved_Amount != null)
                            {
                                total_approved_salary += (decimal)item.Aapproved_Amount;
                            }
                            total_employees = i;
                            if (i % 2 == 0)
                            {
                                selectedRow = "tr-odd";
                            }
                            <tr class="@selectedRow">
                                <td class="col-1"> @i</td>
                                <td class="col-1"> @item.EmployeeData.FIRST_NAME @item.EmployeeData.MID_NAME @item.EmployeeData.LAST_NAME</td>
                                <td class="col-1"> @item.EmployeeData.EMP_NUM</td>
                                <td class="col-1"> @item.Net_Amount</td>
                                <td class="col-1"> @item.Status</td>
                                <td class="col-5">@Html.ActionLink("View", "View_Employee_Payslip", new { id = item.EmployeeData.ID, salary_date = ViewBag.Selected_Salary_Date }) </td>
                            </tr>
                            i += 1;
                        }
                    }
                    <tr class="tr-head">
                        <td class="col-1">Total Employees: </td>
                        <td class="col-1">@total_employees </td>
                        <td class="col-1">Total Salary : </td>
                        <td class="col-1">@total_salary</td>
                        <td class="col-1">Approved Salary: </td>
                        <td class="col-1">@total_approved_salary</td>
                    </tr>
                </table>
                        }
                        else
                        {
                <p class="flash-msg"> No payslip found</p>
            }
        }
    </div>
</div>

SFSAcademy/SFSAcademy/Views/Employee/Edit_Grade.cshtml
@model SFSAcademy.EMPLOYEE_GRADE
@using PagedList.Mvc;

@{
    ViewBag.Title = "Edit_Grade";
}
<div id="content-header">
    <img src="~/Content/images/HR/show_hr.png" alt="HR Logo">
    <h1>Employee Settings</h1>
    <h3>Edit Position</h3>
    <div id="app-back-button">
        <a href='javascript:history.back()' onclick="return confirm('are you sure?')"><img src="~/Content/images/buttons/back.png"></a>
    </div>
</div>
<div><img src="~/Content/images/_global/header_underline_.jpg" style="width:100%"></div>

<div id="page-yield">
    <div id="flash_box">
        @if (ViewBag.Notice != null)
        {
            <p class="flash-msg"> @ViewBag.Notice </p>
        }
    </div>
    @if (ViewBag.ErrorMessage != null)
            {
        <div id="errorExplanation1">
            <ul>
                <li> @ViewBag.ErrorMessage</li>
            </ul>
        </div>
    }
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div id="page-yield">
            @Html.HiddenFor(model => model.ID)
            <div id="form-content">
                <div class="label-field-pair label">
                    @Html.LabelFor(model => model.GRADE_NAME, "Name", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="text-input-bg">
                        @Html.EditorFor(model => model.GRADE_NAME, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.GRADE_NAME, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="label-field-pair label">
                    @Html.LabelFor(model => model.GRADE_CODE, "Grade Code", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="text-input-bg">
                        @Html.EditorFor(model => model.GRADE_CODE, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.GRADE_CODE, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="label-field-pair label">
                    @Html.LabelFor(model => model.DESCR, "Description", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="text-input-bg">
                        @Html.EditorFor(model => model.DESCR, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.DESCR, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="label-field-pair label">
                    @Html.LabelFor(model => model.PRIR, "Priority", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="text-input-bg">
                        @Html.DropDownList("PRIR", new List<SelectListItem>
                                            { new SelectListItem{Text="High", Value="1"},
                                                new SelectListItem{Text="Medium", Value="2"},
                                                new SelectListItem { Text = "Simple", Value = "3" }}, "Select Grade Priority")
                        @Html.ValidationMessageFor(model => model.PRIR, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="label-field-pair label">
                    @Html.LabelFor(model => model.MAX_DILY_HRS, "Max Period Per Day", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="text-input-bg">
                        @Html.EditorFor(model => model.MAX_DILY_HRS, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.MAX_DILY_HRS, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="label-field-pair label">
                    @Html.LabelFor(model => model.MAX_WKILY_HRS, "Max Period Per Week", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="text-input-bg">
                        @Html.EditorFor(model => model.MAX_WKILY_HRS, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.MAX_WKILY_HRS, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="label-checkbox-pair label">
                    <label class="status" for="status">Status:</label>
                    <div id="radio-buttons">
                        @Html.RadioButton("IS_ACT", true, Model.IS_ACT == true ? true : false)@Html.Label("Active", new { @class = "label_for_status" })
                        @Html.RadioButton("IS_ACT", false, Model.IS_ACT == false ? true : false)@Html.Label("Inactive", new { @class = "label_for_status" })
                    </div>
                </div>
                <div id="submit-button">
                    <input type="submit" value="► Update" class="user_button" />
                </div>
            </div>
        </div>
    }


</div>

SFSAcademy/SFSAcademy/Views/Employee/_Attendance_Report.cshtml
@{
    SFSAcademy.EMPLOYEE employee = (SFSAcademy.EMPLOYEE)ViewData["employee"];
    IEnumerable<SFSAcademy.EMPLOYEE_LEAVE_TYPE> leave_types = (IEnumerable<SFSAcademy.EMPLOYEE_LEAVE_TYPE>)ViewData["leave_types"];
    IEnumerable<SFSAcademy.EMPLOYEE_LEAVE> EmployeeLeave = (IEnumerable<SFSAcademy.EMPLOYEE_LEAVE>)ViewData["EmployeeLeave"];
    IEnumerable<SFSAcademy.EMPLOYEE_LEAVE> leave_count = (IEnumerable<SFSAcademy.EMPLOYEE_LEAVE>)ViewData["leave_count"];
    IEnumerable<SFSAcademy.EMPLOYEE_ATTENDENCES> attendance_report = (IEnumerable<SFSAcademy.EMPLOYEE_ATTENDENCES>)ViewData["attendance_report"];
    IEnumerable<SFSAcademy.EMPLOYEE_ATTENDENCES> EmployeeAttendance = (IEnumerable<SFSAcademy.EMPLOYEE_ATTENDENCES>)ViewData["EmployeeAttendance"];
}
<script type="text/javascript" language="javascript">
    //Very similar function as before (except this time with an argument)
    function LoadPartialPage(sender) {
        $(".LoaderBox").show();
        /* Request the partial view with .get request. */
        $.get(sender, function (data) {

            /* data is the pure html returned from action method, load it to your page */
            $('#profile-infos').html(data);
            /* little fade in effect */
            $('#profile-infos').fadeIn('fast');
        }).success(function (status) {
            $(".LoaderBox").hide();
        });
    }

</script>
<div id="attendance-report">
    @{int i = 1;}
    @foreach (var item in leave_types)
    {
        var leave_count_inner = EmployeeLeave.Where(x => x.EMP_LEAVE_TYPE_ID == item.ID && x.EMP_ID == employee.ID).FirstOrDefault();
        string code = "type_nameeven";
        if (i % 2 == 0)
        {
            code = "type_nameodd";
        }
        <div class="@code">@item.NAME:</div>
        var report = EmployeeAttendance.Where(x => x.EMP_ID == employee.ID && x.EMP_LEAVE_TYPE_ID == item.ID).ToList();
        if (leave_count_inner != null && leave_count_inner.RST_DATE != null)
        {
            report = report.Where(x => x.ATNDENCE_DATE >= leave_count_inner.RST_DATE).ToList();
        }
        if (report == null || report.Count() == 0)
        {
            <div class="date-even">No dates found</div>
        }
        else
        {
            foreach (var item2 in report)
            {
                i += 1;
                string code_date = "date-even";
                if (i % 2 == 0)
                {
                    code_date = "date-odd";
                }
                <div class="@code_date">
                    @item2.ATNDENCE_DATE.Value.ToShortDateString()
                    @if (item2.IS_HALF_DAY == true)
                    {
                        <span>Half Day</span>
                    }
                </div>
            }

        }
        i += 1;
    }

    <div class="attendance-stats">
        @{decimal total_leave = 0; int k = 1;
            int month = DateTime.Now.Month;
            DateTime StartDate = new DateTime(DateTime.Now.Year, 4, 1);
            DateTime EndDate = new DateTime(DateTime.Now.Year + 1, 3, 31);
            if (month <= 3)
            {
                StartDate = new DateTime(DateTime.Now.Year - 1, 4, 1);
                EndDate = new DateTime(DateTime.Now.Year, 3, 31);
            }

            int CollectionMonths = Html.GetMonthsBetween(StartDate, EndDate.AddDays(1));
            int CurrCollectionMonths = Html.GetMonthsBetween(StartDate, System.DateTime.Now.AddDays(1));

        }
        @foreach (var item in leave_count)
        {
            var leave_type = leave_types.Where(x => x.ID == item.EMP_LEAVE_TYPE_ID).FirstOrDefault();
            decimal ProratedCount = (decimal)(item.LEAVE_CNT * (CurrCollectionMonths + 1) / CollectionMonths);
            string code2 = "type_nameeven";
            if (k % 2 == 0)
            {
                code2 = "type_nameodd";
            }
            <div class="@code2">
                @if (item.LEAVE_TAKE != null)
                {
                    <div class="total">Total @leave_type.NAME :</div><div class="count">@item.LEAVE_TAKE / @ProratedCount.ToString("0.00")  </div>
                }
                else
                {
                    <div class="total">Total @leave_type.NAME :</div><div class="count">0.00 / @ProratedCount.ToString("0.00") </div>
                }
                @if (Html.Permitted_To("Employee_Leave_Count_Edit", "Employee") || Html.CurrentUser_UserType().Equals("Admin"))
                {
                    <div class="edit-leave"><a href="@Url.Action("Employee_Leave_Count_Edit", "Employee", new { id = item.ID, leave_type_id = item.EMP_LEAVE_TYPE_ID })" class="Profile_Menu" id="EditLeave" onclick='LoadPartialPage(this.href); return false;'>► Edit</a></div>
                }
            </div>
            if (item.LEAVE_TAKE != null)
            {
                total_leave += (decimal)item.LEAVE_TAKE;
            }
            k += 1;
        }

        <div class="type_nameeven"><div class="total">Total Leaves Taken:</div><div class="count">@total_leave</div></div>
    </div>
    <div class="pdf-link">
        <a href="@Url.Action("Employee_Attendance_pdf", "Employee_Attendance",new { id = employee.ID })" class="user_button" title="View pdf Report"><p>► pdf Report</p></a>
    </div>
</div>
<div class="LoaderBox" hidden="hidden"><img src="~/Content/images/loader.gif" id="loader" alt="Data Loading" style="align-self:center; border:none"></div>

SFSAcademy/SFSAcademy/Views/Employee/_One_Click_Payslip_Revert.cshtml
@if (ViewData["Message"].ToString() == "Generated")
{
    <p>Salary Slip Reverted For: @ViewBag.SALARY_DATE.</p>
}
else
{
    <p>Please select appropriate month</p>
}